In [115]:
import pandas as pd

In [116]:
airport_df = pd.read_csv('extracted_airports.csv')
airport_df

,name,iata code,country,city,latitude,longitude,timezone,departures
0,Billy Bishop Toronto City Airport,YTZ,CA,Toronto,43.62974,-79.39828,EST,752.0
1,Kitchener/Waterloo Airport,YKF,CA,Breslau,43.45747,-80.38593,EST,454.0
2,Montreal-Pierre Elliott Trudeau International ...,YUL,CA,Montreal,45.46106,-73.75019,EST,35190.0
3,Ottawa Macdonald-Cartier International Airport,YOW,CA,Ottawa,45.32250,-75.66917,EST,10293.0
4,Toronto Pearson International Airport,YYZ,CA,Toronto,43.68066,-79.61286,EST,72355.0
5,Chicago O'Hare International Airport,ORD,US,Chicago,41.97959,-87.90446,CST,177167.0
6,Dallas/Fort Worth International Airport,DFW,US,Dallas-Ft Worth,32.89595,-97.03720,CST,172447.0
7,Denver International Airport,DEN,US,Denver,39.85891,-104.67326,MST,100565.0
8,Hartsfield-Jackson Atlanta International Airport,ATL,US,Atlanta,33.64099,-84.42265,EST,168164.0
9,Los Angeles International Airport,LAX,US,Los Angeles,33.94251,-118.40897,PST,112571.0

In [117]:
airport_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        10 non-null     object
 1   iata code   10 non-null     object
 2   country     10 non-null     object
 3   city        10 non-null     object
 4   latitude    10 non-null     float64
 5   longitude   10 non-null     float64
 6   timezone    10 non-null     object
 7   departures  10 non-null     float64
dtypes: float64(3), object(5)
memory usage: 768.0+ bytes

In [118]:
# Remove Leading & Trailing Spaces
airport_df = airport_df.astype(str).apply(lambda x: x.str.strip() if x.dtype == 'object' else x)
# Convert 'departures' to numeric, forcing errors to NaN (if there are any non-numeric values)
airport_df['departures'] = pd.to_numeric(airport_df['departures'], errors='coerce')
# Convert to int64 after numeric conversion
airport_df['departures'] = airport_df['departures'].astype('int64')
airport_df['latitude'] = airport_df['departures'].astype(float)
airport_df['longitude'] = airport_df['longitude'].astype(float)

In [119]:
airport_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        10 non-null     object
 1   iata code   10 non-null     object
 2   country     10 non-null     object
 3   city        10 non-null     object
 4   latitude    10 non-null     float64
 5   longitude   10 non-null     float64
 6   timezone    10 non-null     object
 7   departures  10 non-null     int64
dtypes: float64(2), int64(1), object(5)
memory usage: 768.0+ bytes

In [120]:
airport_df.to_csv('cleaned_extracted_airports.csv', index=False)

In [121]:
airlines_df = pd.read_csv('extracted_airlines.csv')
airlines_df

,airline_name,country_code,iata,iosa_registered,iosa_expiry,is_airline_passenger,total_aircrafts,average_fleet_age,accidents_last_5y
0,Alaska Airlines,US,AS,1.0,2025-01-16T00:00:00.000Z,1.0,158.0,8.1,1.0
1,American Airlines,US,AA,1.0,2025-07-29T00:00:00.000Z,1.0,684.0,10.2,26.0
2,Air Canada,CA,AC,1.0,2024-04-18T00:00:00.000Z,1.0,98.0,11.7,0.0
3,Delta Air Lines,US,DL,1.0,2024-10-17T00:00:00.000Z,1.0,591.0,12.5,22.0
4,Envoy Air,US,MQ,1.0,2025-11-18T00:00:00.000Z,1.0,161.0,9.6,0.0
5,Frontier Airlines,US,F9,1.0,2024-01-03T00:00:00.000Z,1.0,83.0,3.0,4.0
6,GOL Linhas Aereas Inteligentes,BR,G3,1.0,2025-11-23T00:00:00.000Z,1.0,103.0,10.7,0.0
7,Jazz Aviation,CA,QK,1.0,2024-10-21T00:00:00.000Z,1.0,85.0,13.8,3.0
8,Lufthansa,DE,LH,1.0,2026-5-12T00:00:00.000Z,1.0,131.0,8.9,1.0
9,Porter Airlines Inc,CA,P3,0.0,NaN,1.0,1.0,8.0,0.0
10,Porter Airlines,CA,PD,0.0,NaN,1.0,1.0,9.0,0.0
11,Republic Airline United Express,US,YX,1.0,2024-12-12T00:00:00.000Z,1.0,182.0,10.1,1.0
12,SkyWest Airlines,US,OO,1.0,2024-09-25T00:00:00.000Z,1.0,462.0,10.7,3.0
13,Spirit Airlines,US,NK,1.0,2025-07-30T00:00:00.000Z,1.0,125.0,4.1,4.0
14,United Airlines,US,UA,1.0,2025-02-26T00:00:00.000Z,1.0,502.0,14.1,12.0
15,Westjet,CA,WS,1.0,2024-11-27T00:00:00.000Z,1.0,70.0,9.8,5.0
16,American Eagle,US,AA,1.0,2024-08-2T00:00:00.000Z,1.0,567.0,10.0,1.0

In [122]:
# Remove Leading & Trailing Spaces
airlines_df = airlines_df.astype(str).apply(lambda x: x.str.strip() if x.dtype == 'object' else x)
airlines_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   airline_name          17 non-null     object
 1   country_code          17 non-null     object
 2   iata                  17 non-null     object
 3   iosa_registered       17 non-null     object
 4   iosa_expiry           17 non-null     object
 5   is_airline_passenger  17 non-null     object
 6   total_aircrafts       17 non-null     object
 7   average_fleet_age     17 non-null     object
 8   accidents_last_5y     17 non-null     object
dtypes: object(9)
memory usage: 1.3+ KB

In [123]:
 # Convert to datetime
airlines_df['iosa_expiry'] = pd.to_datetime(airlines_df['iosa_expiry'], errors='coerce')
# Fill missing value with NAT 
airlines_df['iosa_expiry'] = airlines_df['iosa_expiry'].fillna(pd.NaT)

In [124]:
# Converting float to boolean
airlines_df[['iosa_registered','is_airline_passenger']] =airlines_df[['iosa_registered','is_airline_passenger']].astype(bool)

In [125]:
#Converting float to int
airlines_df[['total_aircrafts','accidents_last_5y']]= airlines_df[['total_aircrafts','accidents_last_5y']].apply(pd.to_numeric, errors='coerce').round(0).astype('int64')

In [126]:
airlines_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   airline_name          17 non-null     object
 1   country_code          17 non-null     object
 2   iata                  17 non-null     object
 3   iosa_registered       17 non-null     bool
 4   iosa_expiry           15 non-null     datetime64[ns, UTC]
 5   is_airline_passenger  17 non-null     bool
 6   total_aircrafts       17 non-null     int64
 7   average_fleet_age     17 non-null     object
 8   accidents_last_5y     17 non-null     int64
dtypes: bool(2), datetime64[ns, UTC](1), int64(2), object(4)
memory usage: 1.1+ KB

In [127]:
airlines_df.to_csv('cleaned_extracted_airlines.csv', index=False)

In [128]:
price_df = pd.read_csv('extracted_price_data.csv')
price_df

,itinerary_id,cabin_class,price_formatted,flight_number,origin_airport,destination_airport,departure_time,arrival_time,stop_count,marketing_airline,operating_airline,is_self_transfer,score,duration_in_hours
0,18467-2504010745--31679-1-10968-2504011249,economy,C$477,6340,YYZ,ATL,2025-04-01T07:45:00,2025-04-01T10:17:00,1,Westjet,Delta Air Lines,False,0.544887,2.53
1,18467-2504010745--31679-1-10968-2504011249,economy,C$477,6482,ATL,DFW,2025-04-01T11:20:00,2025-04-01T12:49:00,1,Westjet,Delta Air Lines,False,0.544887,2.48
2,"18390-2504010700--31954,-31825-2-10968-2504011735",economy,C$253,2205,YTZ,YOW,2025-04-01T07:00:00,2025-04-01T07:59:00,2,Porter Airlines,Porter Airlines Inc,True,0.462699,0.98
3,18467-2504010615--32385-1-10910-2504011111,premium_economy,C$581,2662,YYZ,ATL,2025-04-01T06:15:00,2025-04-01T08:49:00,1,Delta Air Lines,Delta Air Lines,False,0.576769,2.57
4,18467-2504010745--32385-1-10968-2504011249,premium_economy,C$581,2988,YYZ,ATL,2025-04-01T07:45:00,2025-04-01T10:17:00,1,Delta Air Lines,Delta Air Lines,False,0.565300,2.53
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11122,18467-2509300820--31722-0-10968-2509301042,first,C$846,8169,YYZ,DFW,2025-09-30T08:20:00,2025-09-30T10:42:00,0,United Airlines,Air Canada,False,0.668470,3.37
11123,18467-2509301310--32573-1-10968-2509301744,first,C$582,3606,YYZ,ORD,2025-09-30T13:10:00,2025-09-30T14:05:00,1,American Airlines,Envoy Air,False,0.590065,1.92
11124,18467-2509301310--32573-1-10968-2509301744,first,C$582,2429,ORD,DFW,2025-09-30T15:15:00,2025-09-30T17:44:00,1,American Airlines,American Airlines,False,0.590065,2.48
11125,18467-2509301130--32573-1-10968-2509301841,first,C$582,3604,YYZ,ORD,2025-09-30T11:30:00,2025-09-30T12:25:00,1,American Airlines,Envoy Air,False,0.362377,1.92
11126,18467-2509301130--32573-1-10968-2509301841,first,C$582,1193,ORD,DFW,2025-09-30T16:12:00,2025-09-30T18:41:00,1,American Airlines,American Airlines,False,0.362377,2.48

In [129]:
price_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11127 entries, 0 to 11126
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   itinerary_id         11127 non-null  object
 1   cabin_class          11127 non-null  object
 2   price_formatted      11127 non-null  object
 3   flight_number        11127 non-null  int64
 4   origin_airport       11127 non-null  object
 5   destination_airport  11127 non-null  object
 6   departure_time       11127 non-null  object
 7   arrival_time         11127 non-null  object
 8   stop_count           11127 non-null  int64
 9   marketing_airline    11127 non-null  object
 10  operating_airline    11127 non-null  object
 11  is_self_transfer     11127 non-null  bool
 12  score                11127 non-null  float64
 13  duration_in_hours    11127 non-null  float64
dtypes: bool(1), float64(2), int64(2), object(9)
memory usage: 1.1+ MB

In [130]:
# Remove Leading & Trailing Spaces
price_df = price_df.astype(str).apply(lambda x: x.str.strip() if x.dtype == 'object' else x)
price_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11127 entries, 0 to 11126
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   itinerary_id         11127 non-null  object
 1   cabin_class          11127 non-null  object
 2   price_formatted      11127 non-null  object
 3   flight_number        11127 non-null  object
 4   origin_airport       11127 non-null  object
 5   destination_airport  11127 non-null  object
 6   departure_time       11127 non-null  object
 7   arrival_time         11127 non-null  object
 8   stop_count           11127 non-null  object
 9   marketing_airline    11127 non-null  object
 10  operating_airline    11127 non-null  object
 11  is_self_transfer     11127 non-null  object
 12  score                11127 non-null  object
 13  duration_in_hours    11127 non-null  object
dtypes: object(14)
memory usage: 1.2+ MB

In [131]:
# Renaming a single column
price_df = price_df.rename(columns={'price_formatted': 'one_way_price_candollar',
                                    'departure_time':'departure_date_time',
                                    'arrival_time':'arrival_date_time'})
price_df

,itinerary_id,cabin_class,one_way_price_candollar,flight_number,origin_airport,destination_airport,departure_date_time,arrival_date_time,stop_count,marketing_airline,operating_airline,is_self_transfer,score,duration_in_hours
0,18467-2504010745--31679-1-10968-2504011249,economy,C$477,6340,YYZ,ATL,2025-04-01T07:45:00,2025-04-01T10:17:00,1,Westjet,Delta Air Lines,False,0.544887,2.53
1,18467-2504010745--31679-1-10968-2504011249,economy,C$477,6482,ATL,DFW,2025-04-01T11:20:00,2025-04-01T12:49:00,1,Westjet,Delta Air Lines,False,0.544887,2.48
2,"18390-2504010700--31954,-31825-2-10968-2504011735",economy,C$253,2205,YTZ,YOW,2025-04-01T07:00:00,2025-04-01T07:59:00,2,Porter Airlines,Porter Airlines Inc,True,0.462699,0.98
3,18467-2504010615--32385-1-10910-2504011111,premium_economy,C$581,2662,YYZ,ATL,2025-04-01T06:15:00,2025-04-01T08:49:00,1,Delta Air Lines,Delta Air Lines,False,0.576769,2.57
4,18467-2504010745--32385-1-10968-2504011249,premium_economy,C$581,2988,YYZ,ATL,2025-04-01T07:45:00,2025-04-01T10:17:00,1,Delta Air Lines,Delta Air Lines,False,0.5653,2.53
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11122,18467-2509300820--31722-0-10968-2509301042,first,C$846,8169,YYZ,DFW,2025-09-30T08:20:00,2025-09-30T10:42:00,0,United Airlines,Air Canada,False,0.66847,3.37
11123,18467-2509301310--32573-1-10968-2509301744,first,C$582,3606,YYZ,ORD,2025-09-30T13:10:00,2025-09-30T14:05:00,1,American Airlines,Envoy Air,False,0.590065,1.92
11124,18467-2509301310--32573-1-10968-2509301744,first,C$582,2429,ORD,DFW,2025-09-30T15:15:00,2025-09-30T17:44:00,1,American Airlines,American Airlines,False,0.590065,2.48
11125,18467-2509301130--32573-1-10968-2509301841,first,C$582,3604,YYZ,ORD,2025-09-30T11:30:00,2025-09-30T12:25:00,1,American Airlines,Envoy Air,False,0.362377,1.92
11126,18467-2509301130--32573-1-10968-2509301841,first,C$582,1193,ORD,DFW,2025-09-30T16:12:00,2025-09-30T18:41:00,1,American Airlines,American Airlines,False,0.362377,2.48

In [132]:
# Remove 'c$', then remove commas and convert to integer
price_df['one_way_price_candollar'] = price_df['one_way_price_candollar'].replace({'C\$': '', ',': ''}, regex=True).astype('int64')

In [133]:
# Convert flight_number to integer
price_df[['flight_number','stop_count']] = price_df[['flight_number','stop_count']].astype('int64')

In [134]:
price_df['departure_date_time']=pd.to_datetime(price_df['departure_date_time'], errors='coerce')

In [135]:
price_df['arrival_date_time']=pd.to_datetime(price_df['arrival_date_time'], errors='coerce')

In [136]:
price_df[['score','duration_in_hours']] = price_df[['score','duration_in_hours']].astype(float)

In [137]:
price_df['is_self_transfer'] = price_df['is_self_transfer'].astype(bool)

In [138]:
price_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11127 entries, 0 to 11126
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   itinerary_id             11127 non-null  object
 1   cabin_class              11127 non-null  object
 2   one_way_price_candollar  11127 non-null  int64
 3   flight_number            11127 non-null  int64
 4   origin_airport           11127 non-null  object
 5   destination_airport      11127 non-null  object
 6   departure_date_time      11127 non-null  datetime64[ns]
 7   arrival_date_time        11127 non-null  datetime64[ns]
 8   stop_count               11127 non-null  int64
 9   marketing_airline        11127 non-null  object
 10  operating_airline        11127 non-null  object
 11  is_self_transfer         11127 non-null  bool
 12  score                    11127 non-null  float64
 13  duration_in_hours        11127 non-null  float64
dtypes: bool(1), datetime64[ns](2), float64(2), int64(3), object(6)
memory usage: 1.1+ MB

In [139]:
price_df.to_csv('cleaned_price_data.csv', index=False)