### For this project, the flight price dataset is available from specific US and Canada airports to specific US airports.
### The data is available from March 2025 to 10th February, 2026. 
### The data is retrieved using some of the API endpoints of Goflightlab.

# Data cleaning strategy
### Save the selected airport's details, extracted from the airport_data file into a csv, after cleaning the dataset.
### Save the required airlines information, extracted from the airlines_list file into a csv, after cleaning the dataset.
### Save the flight price dataset in a csv, after necessary cleaning.

In [1]:
# import dependencies
# Import the pandas library for data manipulation and analysis
import pandas as pd
# Import the glob module to find all file paths matching a pattern
import glob

# 1. Import Canada and US airports dataset.

### Concatenate Canada and US airports information. From the concatenated dataset, retrieve only the required airports. They are
#### CANADAN AIRPORTS  --- 1.Toronto Island(YTZ)      2.Ottawa International(YOW)       3.Toronto Pearson International(YYZ)                       
#### 4.Montreal Pierre Elliott Trudeau (YUL)                                                                        
#### US AIRPORTS --- 1.Dallas Fort Worth International(DFW)  2.Denver International(DEN)   3.Atlanta Hartsfield-Jackson(ATL)  4.Chicago O'Hare International(ORD)
#### 5.Los Angeles International(LAX)

In [2]:
# Read in the Canada airport data
canada_airport_data = pd.read_csv("Resources/raw_data/airport_data/airport_data_CA.csv")
canada_airport_data.head()

,Name,IATA Code,ICAO Code,Country,City,City Code,Latitude,Longitude,Timezone,Departures
0,Abbotsford International Airport,YXX,CYXX,CA,Abbotsford,YVR,49.02529,-122.37735,America/Vancouver,941.0
1,Aklavik/Freddie Carmichael Airport,LAK,CYKD,CA,Aklavik,LAK,68.22333,-135.00583,America/Yellowknife,348.0
2,Akulivik Airport,AKV,CYKO,CA,Akulivik,AKV,60.81861,-78.14861,America/Toronto,270.0
3,Alberni Valley Regional Airport,YPB,NaN,CA,Port Alberni,YPB,49.31933,-124.92979,America/Vancouver,NaN
4,Alert Bay Airport,YAL,CYAL,CA,Alert Bay,NaN,50.58220,-126.91600,America/Vancouver,NaN

In [3]:
# Read in the US airport data
us_airport_data = pd.read_csv("Resources/raw_data/airport_data/airport_data_US.csv")
us_airport_data.head()

,Name,IATA Code,ICAO Code,Country,City,City Code,Latitude,Longitude,Timezone,Departures
0,A L Mangham Jr. Regional Airport,OCH,KOCH,US,Nacogdoches,OCH,31.577880,-94.706680,America/Chicago,NaN
1,A P Hill Army Airfield (Fort A P Hill),APH,KAPH,US,Bowling Green,NaN,38.069680,-77.318090,America/New_York,NaN
2,Aban Uqua Airportse,QKA,KQKA,US,KXXQO City,NaN,-14.735092,-91.112751,Etc/GMT+6,NaN
3,Abbeville Chris Crusta Memorial Airport,NaN,KIYA,US,New Iberia,ARA,29.971610,-92.084700,America/Chicago,NaN
4,Aberdeen Regional Airport,ABR,KABR,US,Aberdeen,ABR,45.449700,-98.421480,America/Chicago,374.0

In [4]:
# concat canada and us airport data
merged_canada_us_airport_data = pd.concat([canada_airport_data, us_airport_data])
merged_canada_us_airport_data.head()

,Name,IATA Code,ICAO Code,Country,City,City Code,Latitude,Longitude,Timezone,Departures
0,Abbotsford International Airport,YXX,CYXX,CA,Abbotsford,YVR,49.02529,-122.37735,America/Vancouver,941.0
1,Aklavik/Freddie Carmichael Airport,LAK,CYKD,CA,Aklavik,LAK,68.22333,-135.00583,America/Yellowknife,348.0
2,Akulivik Airport,AKV,CYKO,CA,Akulivik,AKV,60.81861,-78.14861,America/Toronto,270.0
3,Alberni Valley Regional Airport,YPB,NaN,CA,Port Alberni,YPB,49.31933,-124.92979,America/Vancouver,NaN
4,Alert Bay Airport,YAL,CYAL,CA,Alert Bay,NaN,50.58220,-126.91600,America/Vancouver,NaN

##### Filtering the merged airport data to get the required Canadian and US airport

In [5]:
# Filter the merged Canada-US airport dataset to include only the busiest airports based on their IATA codes.
can_us_busiest_airport = merged_canada_us_airport_data.loc[merged_canada_us_airport_data['IATA Code'].isin(["YUL", "YYZ", "YTZ", "YOW", "YKF", "ATL", "DFW", "DEN", "ORD","LAX"])]

#Reset the index of the filtered DataFrame to ensure it starts from 0 and remove the old index
filtered_airports = can_us_busiest_airport.reset_index(drop=True) 

# Display the filtered DataFrame
filtered_airports

,Name,IATA Code,ICAO Code,Country,City,City Code,Latitude,Longitude,Timezone,Departures
0,Billy Bishop Toronto City Airport,YTZ,CYTZ,CA,Toronto,YTO,43.62974,-79.39828,America/Toronto,752.0
1,Kitchener/Waterloo Airport,YKF,CYKF,CA,Breslau,YKF,43.45747,-80.38593,America/Toronto,454.0
2,Montreal-Pierre Elliott Trudeau International ...,YUL,CYUL,CA,Montreal,YMQ,45.46106,-73.75019,America/Toronto,35190.0
3,Ottawa Macdonald-Cartier International Airport,YOW,CYOW,CA,Ottawa,YOW,45.32250,-75.66917,America/Toronto,10293.0
4,Toronto Pearson International Airport,YYZ,CYYZ,CA,Toronto,YTO,43.68066,-79.61286,America/Toronto,72355.0
5,Chicago O'Hare International Airport,ORD,KORD,US,Chicago,CHI,41.97959,-87.90446,America/Chicago,177167.0
6,Dallas/Fort Worth International Airport,DFW,KDFW,US,Dallas-Ft Worth,DFW,32.89595,-97.03720,America/Chicago,172447.0
7,Denver International Airport,DEN,KDEN,US,Denver,DEN,39.85891,-104.67326,America/Denver,100565.0
8,Hartsfield-Jackson Atlanta International Airport,ATL,KATL,US,Atlanta,ATL,33.64099,-84.42265,America/New_York,168164.0
9,Los Angeles International Airport,LAX,KLAX,US,Los Angeles,LAX,33.94251,-118.40897,America/Los_Angeles,112571.0

##### Dropping unwanted columns

In [6]:
# Define a list of columns to drop from the DataFrame
column_to_drop = ["ICAO Code","City Code"]

# Drop the specified columns from the filtered_airports DataFrame. The "errors='ignore'" parameter ensures that if the columns are not found, no error is raised
filtered_airports = filtered_airports.drop(columns=column_to_drop, errors="ignore")

# Reset the index of the DataFrame to maintain sequential ordering. The "inplace=True" parameter modifies the DataFrame directly without creating a copy
filtered_airports.reset_index(drop=True, inplace=True)
filtered_airports

,Name,IATA Code,Country,City,Latitude,Longitude,Timezone,Departures
0,Billy Bishop Toronto City Airport,YTZ,CA,Toronto,43.62974,-79.39828,America/Toronto,752.0
1,Kitchener/Waterloo Airport,YKF,CA,Breslau,43.45747,-80.38593,America/Toronto,454.0
2,Montreal-Pierre Elliott Trudeau International ...,YUL,CA,Montreal,45.46106,-73.75019,America/Toronto,35190.0
3,Ottawa Macdonald-Cartier International Airport,YOW,CA,Ottawa,45.32250,-75.66917,America/Toronto,10293.0
4,Toronto Pearson International Airport,YYZ,CA,Toronto,43.68066,-79.61286,America/Toronto,72355.0
5,Chicago O'Hare International Airport,ORD,US,Chicago,41.97959,-87.90446,America/Chicago,177167.0
6,Dallas/Fort Worth International Airport,DFW,US,Dallas-Ft Worth,32.89595,-97.03720,America/Chicago,172447.0
7,Denver International Airport,DEN,US,Denver,39.85891,-104.67326,America/Denver,100565.0
8,Hartsfield-Jackson Atlanta International Airport,ATL,US,Atlanta,33.64099,-84.42265,America/New_York,168164.0
9,Los Angeles International Airport,LAX,US,Los Angeles,33.94251,-118.40897,America/Los_Angeles,112571.0

##### Update TimeZone column

In [7]:
# Replace specific timezone values in the 'Timezone' column with corresponding standard time zone abbreviations
filtered_airports['Timezone'] = filtered_airports['Timezone'].replace({'America/Toronto': 'EST',
                                                                       'America/Chicago': 'CST',
                                                                       'America/Denver': 'MST',
                                                                       'America/New_York':'EST', 
                                                                        'America/Los_Angeles':'PST'                                                                           
                                                                       })

In [8]:
filtered_airports.columns = filtered_airports.columns.str.lower()
filtered_airports

,name,iata code,country,city,latitude,longitude,timezone,departures
0,Billy Bishop Toronto City Airport,YTZ,CA,Toronto,43.62974,-79.39828,EST,752.0
1,Kitchener/Waterloo Airport,YKF,CA,Breslau,43.45747,-80.38593,EST,454.0
2,Montreal-Pierre Elliott Trudeau International ...,YUL,CA,Montreal,45.46106,-73.75019,EST,35190.0
3,Ottawa Macdonald-Cartier International Airport,YOW,CA,Ottawa,45.32250,-75.66917,EST,10293.0
4,Toronto Pearson International Airport,YYZ,CA,Toronto,43.68066,-79.61286,EST,72355.0
5,Chicago O'Hare International Airport,ORD,US,Chicago,41.97959,-87.90446,CST,177167.0
6,Dallas/Fort Worth International Airport,DFW,US,Dallas-Ft Worth,32.89595,-97.03720,CST,172447.0
7,Denver International Airport,DEN,US,Denver,39.85891,-104.67326,MST,100565.0
8,Hartsfield-Jackson Atlanta International Airport,ATL,US,Atlanta,33.64099,-84.42265,EST,168164.0
9,Los Angeles International Airport,LAX,US,Los Angeles,33.94251,-118.40897,PST,112571.0

##### Save the cleaned airportas extracted_airports.csv

In [9]:
filtered_airports.to_csv("extracted_airports.csv", index=False)

# 2. Import flight price dataset 
##### Loop through each month's flight price data to get a year  dataset.
##### Convert the departure_time and arrival_time fields to datetime format. 
##### Split the departure_time to Departure Date and Departure Time and  arrival_time to Arrival Date and Arrival Time.
##### Drop unwanted columns.
##### Retrieve only the required airports dataset.
##### Confirm that only the required airports data is retrieved.
##### Find the unique airline names from marketing_airline and operating_airline columns.

In [10]:
# Define the pattern to match all the flight price CSV files
file_pattern = "Resources/raw_data/flight_price_data/flight_data_full_*.csv"

In [11]:
# Get a list of matching CSV file names
csv_files = glob.glob(file_pattern)
csv_files

['Resources/raw_data/flight_price_data\\flight_data_full_April.csv',
 'Resources/raw_data/flight_price_data\\flight_data_full_August.csv',
 'Resources/raw_data/flight_price_data\\flight_data_full_December.csv',
 'Resources/raw_data/flight_price_data\\flight_data_full_February2026.csv',
 'Resources/raw_data/flight_price_data\\flight_data_full_January2026.csv',
 'Resources/raw_data/flight_price_data\\flight_data_full_July.csv',
 'Resources/raw_data/flight_price_data\\flight_data_full_June.csv',
 'Resources/raw_data/flight_price_data\\flight_data_full_March.csv',
 'Resources/raw_data/flight_price_data\\flight_data_full_May.csv',
 'Resources/raw_data/flight_price_data\\flight_data_full_November.csv',
 'Resources/raw_data/flight_price_data\\flight_data_full_October.csv',
 'Resources/raw_data/flight_price_data\\flight_data_full_September.csv']

In [12]:

# Create an empty list to store dataframes
flight_price_full_year = []
# Loop through each file and read it into a dataframe
for file in csv_files:
    # Read CSV
    flight_price_df = pd.read_csv(file)  

    # Append dataframe to list
    flight_price_full_year.append(flight_price_df)

In [13]:
# Combine all dataframes in the list into a single DataFrame
flight_price_full_year_df = pd.concat(flight_price_full_year, ignore_index=True)
flight_price_full_year_df

,date,itinerary_id,cabin_class,sort_by,price_raw,price_formatted,currency,flight_number,origin_airport,origin_city,...,arrival_time,duration_minutes,stop_count,marketing_airline,operating_airline,change_allowed,cancellation_allowed,is_self_transfer,has_flexible_options,score
0,4/1/2025,18467-2504011020--31679-1-10968-2504011436,economy,fastest,476.60,C$477,NaN,5545,Toronto Pearson International,NaN,...,2025-04-01T11:39:00,79,1,WestJet,SkyWest DBA Delta Connection,False,False,False,False,0.999000
1,4/1/2025,18467-2504011020--31679-1-10968-2504011436,economy,fastest,476.60,C$477,NaN,8400,Detroit Wayne County,NaN,...,2025-04-01T14:36:00,176,1,WestJet,Delta,False,False,False,False,0.999000
2,4/1/2025,18467-2504010600--31679-1-10968-2504011037,economy,fastest,476.60,C$477,NaN,6342,Toronto Pearson International,NaN,...,2025-04-01T07:32:00,92,1,WestJet,Endeavor Air DBA Delta Connection,False,False,False,False,0.611641
3,4/1/2025,18467-2504010600--31679-1-10968-2504011037,economy,fastest,476.60,C$477,NaN,7021,Detroit Wayne County,NaN,...,2025-04-01T10:37:00,186,1,WestJet,Delta,False,False,False,False,0.611641
4,4/1/2025,18467-2504011320--31679-1-10968-2504011758,economy,fastest,476.60,C$477,NaN,6343,Toronto Pearson International,NaN,...,2025-04-01T14:36:00,76,1,WestJet,Endeavor Air DBA Delta Connection,False,False,False,False,0.627755
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22124,2025-09-30,18467-2509301540--32573-1-10968-2509302150,first,fastest,581.49,C$582,NaN,3108,Charlotte Douglas,NaN,...,2025-09-30T21:50:00,155,1,American Airlines,American Airlines,False,False,False,False,0.352783
22125,2025-09-30,18467-2509300725--32573-1-10968-2509301342,first,fastest,581.49,C$582,NaN,4559,Toronto Pearson International,NaN,...,2025-09-30T09:10:00,105,1,American Airlines,Republic Airways AS American Eagle,False,False,False,False,0.380391
22126,2025-09-30,18467-2509300725--32573-1-10968-2509301342,first,fastest,581.49,C$582,NaN,2697,New York John F. Kennedy,NaN,...,2025-09-30T13:42:00,232,1,American Airlines,American Airlines,False,False,False,False,0.380391
22127,2025-09-30,18467-2509301130--32573-1-10968-2509301841,first,fastest,581.49,C$582,NaN,3604,Toronto Pearson International,NaN,...,2025-09-30T12:25:00,115,1,American Airlines,Envoy Air As American Eagle,False,False,False,False,0.362377
22128,2025-09-30,18467-2509301130--32573-1-10968-2509301841,first,fastest,581.49,C$582,NaN,1193,Chicago O'Hare International,NaN,...,2025-09-30T18:41:00,149,1,American Airlines,American Airlines,False,False,False,False,0.362377

In [14]:
flight_price_full_year_df.to_csv('full_year.csv', index=False)

In [15]:
flight_price_full_year_df

,date,itinerary_id,cabin_class,sort_by,price_raw,price_formatted,currency,flight_number,origin_airport,origin_city,...,arrival_time,duration_minutes,stop_count,marketing_airline,operating_airline,change_allowed,cancellation_allowed,is_self_transfer,has_flexible_options,score
0,4/1/2025,18467-2504011020--31679-1-10968-2504011436,economy,fastest,476.60,C$477,NaN,5545,Toronto Pearson International,NaN,...,2025-04-01T11:39:00,79,1,WestJet,SkyWest DBA Delta Connection,False,False,False,False,0.999000
1,4/1/2025,18467-2504011020--31679-1-10968-2504011436,economy,fastest,476.60,C$477,NaN,8400,Detroit Wayne County,NaN,...,2025-04-01T14:36:00,176,1,WestJet,Delta,False,False,False,False,0.999000
2,4/1/2025,18467-2504010600--31679-1-10968-2504011037,economy,fastest,476.60,C$477,NaN,6342,Toronto Pearson International,NaN,...,2025-04-01T07:32:00,92,1,WestJet,Endeavor Air DBA Delta Connection,False,False,False,False,0.611641
3,4/1/2025,18467-2504010600--31679-1-10968-2504011037,economy,fastest,476.60,C$477,NaN,7021,Detroit Wayne County,NaN,...,2025-04-01T10:37:00,186,1,WestJet,Delta,False,False,False,False,0.611641
4,4/1/2025,18467-2504011320--31679-1-10968-2504011758,economy,fastest,476.60,C$477,NaN,6343,Toronto Pearson International,NaN,...,2025-04-01T14:36:00,76,1,WestJet,Endeavor Air DBA Delta Connection,False,False,False,False,0.627755
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22124,2025-09-30,18467-2509301540--32573-1-10968-2509302150,first,fastest,581.49,C$582,NaN,3108,Charlotte Douglas,NaN,...,2025-09-30T21:50:00,155,1,American Airlines,American Airlines,False,False,False,False,0.352783
22125,2025-09-30,18467-2509300725--32573-1-10968-2509301342,first,fastest,581.49,C$582,NaN,4559,Toronto Pearson International,NaN,...,2025-09-30T09:10:00,105,1,American Airlines,Republic Airways AS American Eagle,False,False,False,False,0.380391
22126,2025-09-30,18467-2509300725--32573-1-10968-2509301342,first,fastest,581.49,C$582,NaN,2697,New York John F. Kennedy,NaN,...,2025-09-30T13:42:00,232,1,American Airlines,American Airlines,False,False,False,False,0.380391
22127,2025-09-30,18467-2509301130--32573-1-10968-2509301841,first,fastest,581.49,C$582,NaN,3604,Toronto Pearson International,NaN,...,2025-09-30T12:25:00,115,1,American Airlines,Envoy Air As American Eagle,False,False,False,False,0.362377
22128,2025-09-30,18467-2509301130--32573-1-10968-2509301841,first,fastest,581.49,C$582,NaN,1193,Chicago O'Hare International,NaN,...,2025-09-30T18:41:00,149,1,American Airlines,American Airlines,False,False,False,False,0.362377

##### Converting duration from minutes to hours

In [16]:
flight_price_full_year_df['duration_in_hours'] = (flight_price_full_year_df['duration_minutes']/60).round(2)

##### Remove unwanted columns from flight price dataset.

In [17]:
columns_to_drop = [
        "sort_by", "price_raw", "origin_city", "origin_country", "currency",
        "destination_city", "destination_country", "change_allowed", 
        "cancellation_allowed", "has_flexible_options","date",'duration_minutes'
    ]
flight_price_full_year_df = flight_price_full_year_df.drop(columns=columns_to_drop, errors="ignore")
flight_price_full_year_df.reset_index(drop=True, inplace=True)
flight_price_full_year_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22129 entries, 0 to 22128
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   itinerary_id         22129 non-null  object
 1   cabin_class          22129 non-null  object
 2   price_formatted      22129 non-null  object
 3   flight_number        22129 non-null  int64
 4   origin_airport       22129 non-null  object
 5   destination_airport  22129 non-null  object
 6   departure_time       22129 non-null  object
 7   arrival_time         22129 non-null  object
 8   stop_count           22129 non-null  int64
 9   marketing_airline    22129 non-null  object
 10  operating_airline    22129 non-null  object
 11  is_self_transfer     22129 non-null  bool
 12  score                22129 non-null  float64
 13  duration_in_hours    22129 non-null  float64
dtypes: bool(1), float64(2), int64(2), object(9)
memory usage: 2.2+ MB

##### Retrieve data of selected airports only.

In [18]:
# Select only specific airports data in the flight_price dataset
selected_airports = {"Toronto Island","Ottawa International",
                     "Toronto Pearson International", "Chicago O'Hare International",
                     "Dallas Fort Worth International","Denver International",
                     "Atlanta Hartsfield-Jackson","Montreal Pierre Elliott Trudeau",
                     "Los Angeles International"
                     }

selected_flight_price_data =  flight_price_full_year_df[ flight_price_full_year_df['origin_airport'].isin(selected_airports) &  flight_price_full_year_df['destination_airport'].isin(selected_airports)]

In [19]:
selected_flight_price_data

,itinerary_id,cabin_class,price_formatted,flight_number,origin_airport,destination_airport,departure_time,arrival_time,stop_count,marketing_airline,operating_airline,is_self_transfer,score,duration_in_hours
8,18467-2504010745--31679-1-10968-2504011249,economy,C$477,6340,Toronto Pearson International,Atlanta Hartsfield-Jackson,2025-04-01T07:45:00,2025-04-01T10:17:00,1,WestJet,Delta,False,0.544887,2.53
9,18467-2504010745--31679-1-10968-2504011249,economy,C$477,6482,Atlanta Hartsfield-Jackson,Dallas Fort Worth International,2025-04-01T11:20:00,2025-04-01T12:49:00,1,WestJet,Delta,False,0.544887,2.48
16,"18390-2504010700--31954,-31825-2-10968-2504011735",economy,C$253,2205,Toronto Island,Ottawa International,2025-04-01T07:00:00,2025-04-01T07:59:00,2,Porter Airlines (Canada) Ltd,Porter Airlines Inc,True,0.462699,0.98
29,18467-2504010615--32385-1-10910-2504011111,premium_economy,C$581,2662,Toronto Pearson International,Atlanta Hartsfield-Jackson,2025-04-01T06:15:00,2025-04-01T08:49:00,1,Delta,Delta,False,0.576769,2.57
31,18467-2504010745--32385-1-10968-2504011249,premium_economy,C$581,2988,Toronto Pearson International,Atlanta Hartsfield-Jackson,2025-04-01T07:45:00,2025-04-01T10:17:00,1,Delta,Delta,False,0.565300,2.53
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22112,18467-2509300820--31722-0-10968-2509301042,first,C$846,8169,Toronto Pearson International,Dallas Fort Worth International,2025-09-30T08:20:00,2025-09-30T10:42:00,0,United,Air Canada,False,0.668470,3.37
22113,18467-2509301310--32573-1-10968-2509301744,first,C$582,3606,Toronto Pearson International,Chicago O'Hare International,2025-09-30T13:10:00,2025-09-30T14:05:00,1,American Airlines,Envoy Air As American Eagle,False,0.590065,1.92
22114,18467-2509301310--32573-1-10968-2509301744,first,C$582,2429,Chicago O'Hare International,Dallas Fort Worth International,2025-09-30T15:15:00,2025-09-30T17:44:00,1,American Airlines,American Airlines,False,0.590065,2.48
22127,18467-2509301130--32573-1-10968-2509301841,first,C$582,3604,Toronto Pearson International,Chicago O'Hare International,2025-09-30T11:30:00,2025-09-30T12:25:00,1,American Airlines,Envoy Air As American Eagle,False,0.362377,1.92
22128,18467-2509301130--32573-1-10968-2509301841,first,C$582,1193,Chicago O'Hare International,Dallas Fort Worth International,2025-09-30T16:12:00,2025-09-30T18:41:00,1,American Airlines,American Airlines,False,0.362377,2.48

##### Confirm that all retrieved records are of selected airports.

In [20]:
# Confirming that only those records with required airports were selected 
airports = pd.Series(list(set(selected_flight_price_data['origin_airport']) | set(selected_flight_price_data['destination_airport'])))  # Union of both
airports

0       Chicago O'Hare International
1    Dallas Fort Worth International
2                     Toronto Island
3               Ottawa International
4    Montreal Pierre Elliott Trudeau
5               Denver International
6         Atlanta Hartsfield-Jackson
7      Toronto Pearson International
8          Los Angeles International
dtype: object

In [21]:
iata_dict={
    "Toronto Island":"YTZ",
    "Ottawa International":"YOW",
    "Toronto Pearson International":"YYZ",
    "Chicago O'Hare International":"ORD",
    "Dallas Fort Worth International":"DFW",
    "Denver International":"DEN",
    "Atlanta Hartsfield-Jackson":"ATL",
    "Montreal Pierre Elliott Trudeau":"YUL",
    "Los Angeles International":"LAX"
}   

# Map IATA code to airport name
selected_flight_price_data.loc[:, 'origin_airport'] = selected_flight_price_data['origin_airport'].map(iata_dict)
selected_flight_price_data.loc[:, 'destination_airport'] = selected_flight_price_data['destination_airport'].map(iata_dict)
selected_flight_price_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11127 entries, 8 to 22128
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   itinerary_id         11127 non-null  object
 1   cabin_class          11127 non-null  object
 2   price_formatted      11127 non-null  object
 3   flight_number        11127 non-null  int64
 4   origin_airport       11127 non-null  object
 5   destination_airport  11127 non-null  object
 6   departure_time       11127 non-null  object
 7   arrival_time         11127 non-null  object
 8   stop_count           11127 non-null  int64
 9   marketing_airline    11127 non-null  object
 10  operating_airline    11127 non-null  object
 11  is_self_transfer     11127 non-null  bool
 12  score                11127 non-null  float64
 13  duration_in_hours    11127 non-null  float64
dtypes: bool(1), float64(2), int64(2), object(9)
memory usage: 1.2+ MB

##### Retrieve unique airline names from marketing_airline and operating_airline columns of flight price data

In [22]:
# retrieve unique airlines from marketing airline and operating airline fields of the required data
unique_airlines = pd.Series(list(set(selected_flight_price_data['operating_airline']) | set(selected_flight_price_data['marketing_airline'])))  # Union of both
unique_airlines

0                       Frontier Airlines
1                              Air Canada
2                       American Airlines
3                              GOL Linhas
4      Republic Airways AS American Eagle
5                     Porter Airlines Inc
6                                  United
7                         Spirit Airlines
8            Porter Airlines (Canada) Ltd
9                               Lufthansa
10                                  Delta
11    Republic Airways DBA United Express
12            Envoy Air As American Eagle
13                                WestJet
14                        Alaska Airlines
15             SkyWest DBA United Express
16              Air Canada Express - Jazz
dtype: object

# 3. Import Airlines dataset

In [23]:
# Read in the  Airline dataset
airlines_data = pd.read_csv("Resources/raw_data/airlines_list_data.csv")
airlines_data.head()

,Name,country_code,iata_code,iata_prefix,iata_accounting,callsign,is international,iosa_registered,iosa_expiry,is_passenger,...,is_scheduled,total_aircrafts,average_fleet_age,accidents_last_5y,crashes_last_5y,website,twitter,facebook,instagram,linkedin
0,10 Tanker Air Carrier,US,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,135 Airways,US,NaN,NaN,NaN,GENERAL,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1903 Aviation,SE,NaN,NaN,NaN,HIGHSCORE,NaN,NaN,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Air 1st Aviation Companies of Oklahoma,US,NaN,NaN,NaN,ROUGHRIDER,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"2 Sqn, No 1 Elementary Flying Training School",UK,NaN,NaN,NaN,WYTON,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

##### Retrieve only required airline names (as per the unique airline names of flight price dataset) from airline dataset.

In [24]:
# Get only the required airline names from airline dataset
available_airlines = airlines_data.loc[airlines_data['iata_code'].isin(["OO", "MQ", "F9", "DL", "YX", "LH", "PD", "WS", "AA","UA","QK","AS","AC","NK","G3","P3"])]
airlines_info = available_airlines.reset_index(drop=True) 
airlines_info

,Name,country_code,iata_code,iata_prefix,iata_accounting,callsign,is international,iosa_registered,iosa_expiry,is_passenger,...,is_scheduled,total_aircrafts,average_fleet_age,accidents_last_5y,crashes_last_5y,website,twitter,facebook,instagram,linkedin
0,Alaska Airlines,US,AS,27.0,27.0,ALASKA,NaN,1.0,2025-01-16T00:00:00.000Z,1.0,...,1.0,158.0,8.1,1.0,0.0,NaN,NaN,facebook.com/alaskaairlines,instagram.com/alaskaair,NaN
1,American Airlines,US,AA,1.0,1.0,AMERICAN,NaN,1.0,2025-07-29T00:00:00.000Z,1.0,...,1.0,684.0,10.2,26.0,0.0,NaN,NaN,facebook.com/aa,instagram.com/americanair,linkedin.com/company/american-airlines
2,Air Canada,CA,AC,14.0,14.0,AIRCANADA,NaN,1.0,2024-04-18T00:00:00.000Z,1.0,...,1.0,98.0,11.7,0.0,0.0,NaN,NaN,facebook.com/aircanada,instagram.com/_u/aircanada,NaN
3,Delta Air Lines,US,DL,6.0,6.0,DELTA,NaN,1.0,2024-10-17T00:00:00.000Z,1.0,...,1.0,591.0,12.5,22.0,0.0,NaN,NaN,facebook.com/delta,instagram.com/delta/,linkedin.com/company/delta-air-lines
4,Envoy Air,US,MQ,93.0,93.0,ENVOY,NaN,1.0,2025-11-18T00:00:00.000Z,1.0,...,1.0,161.0,9.6,0.0,0.0,NaN,NaN,facebook.com/envoyaircareers,instagram.com/envoyaircareers/,linkedin.com/company/envoyair
5,Frontier Airlines,US,F9,422.0,422.0,FRONTIERFLIGHT,NaN,1.0,2024-01-03T00:00:00.000Z,1.0,...,1.0,83.0,3.0,4.0,0.0,NaN,NaN,NaN,NaN,NaN
6,GOL Linhas Aereas Inteligentes,BR,G3,127.0,127.0,GOLTRANSPORTE,NaN,1.0,2025-11-23T00:00:00.000Z,1.0,...,1.0,103.0,10.7,0.0,0.0,NaN,NaN,NaN,instagram.com/voegoloficial,linkedin.com/company/gol
7,Jazz Aviation,CA,QK,NaN,NaN,JAZZ,NaN,1.0,2024-10-21T00:00:00.000Z,1.0,...,1.0,85.0,13.8,3.0,0.0,NaN,NaN,facebook.com/JobsAtJazz,instagram.com/jazzaviationlp/,linkedin.com/company/jazz-aviation-lp/
8,Lufthansa Cargo,DE,LH,20.0,20.0,LUFTHANSACARGO,NaN,1.0,2026-02-02T00:00:00.000Z,NaN,...,1.0,15.0,10.7,0.0,0.0,NaN,NaN,facebook.com/lufthansacargoag,instagram.com/lufthansacargoag/,linkedin.com/company/lufthansa-cargo
9,Lufthansa,DE,LH,220.0,220.0,LUFTHANSA,NaN,1.0,2026-5-12T00:00:00.000Z,1.0,...,1.0,131.0,8.9,1.0,0.0,NaN,NaN,facebook.com/Lufthansa,instagram.com/lufthansa/,NaN
10,Porter Airlines Inc,CA,P3,NaN,NaN,DASHPORT,NaN,0.0,NaN,1.0,...,1.0,1.0,8.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
11,Porter Airlines,CA,PD,NaN,NaN,PORTERAIR,NaN,0.0,NaN,1.0,...,1.0,1.0,9.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
12,Republic Airline United Express,US,YX,453.0,453.0,BRICKYARD,NaN,1.0,2024-12-12T00:00:00.000Z,1.0,...,1.0,182.0,10.1,1.0,NaN,NaN,NaN,facebook.com/republicairline,instagram.com/RepublicAirline/,linkedin.com/company/768161/
13,SkyWest Airlines,US,OO,302.0,302.0,SKYWEST,NaN,1.0,2024-09-25T00:00:00.000Z,1.0,...,1.0,462.0,10.7,3.0,0.0,NaN,NaN,NaN,NaN,NaN
14,Spirit Airlines,US,NK,487.0,487.0,SPIRITWINGS,NaN,1.0,2025-07-30T00:00:00.000Z,1.0,...,1.0,125.0,4.1,4.0,0.0,NaN,NaN,NaN,NaN,NaN
15,United Airlines,US,UA,16.0,16.0,UNITED,NaN,1.0,2025-02-26T00:00:00.000Z,1.0,...,1.0,502.0,14.1,12.0,0.0,NaN,NaN,NaN,NaN,NaN
16,Westjet,CA,WS,838.0,838.0,WESTJET,NaN,1.0,2024-11-27T00:00:00.000Z,1.0,...,1.0,70.0,9.8,5.0,0.0,NaN,NaN,NaN,NaN,NaN
17,American Eagle,US,AA,2.0,2.0,AMERICA,NaN,1.0,2024-08-2T00:00:00.000Z,1.0,...,1.0,567.0,10.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
# Fetch airline column names
airlines_info.columns

Index(['Name', 'country_code', 'iata_code', 'iata_prefix', 'iata_accounting',
       'callsign', 'is international', 'iosa_registered', 'iosa_expiry',
       'is_passenger', 'is_cargo', 'is_scheduled', 'total_aircrafts',
       'average_fleet_age', 'accidents_last_5y', 'crashes_last_5y', 'website',
       'twitter', 'facebook', 'instagram', 'linkedin'],
      dtype='object')

##### Remove unwanted columns

In [26]:
fields_to_drop = [
       'iata_prefix', 'iata_accounting',
       'callsign', 'is international','is_passenger', 'is_cargo', 'website',
       'twitter', 'facebook', 'instagram', 'linkedin','crashes_last_5y'
    ]
wanted_airlines_fields = airlines_info.drop(columns=fields_to_drop, errors="ignore")
wanted_airlines_fields.reset_index(drop=True, inplace=True)

In [27]:
wanted_airlines_fields

,Name,country_code,iata_code,iosa_registered,iosa_expiry,is_scheduled,total_aircrafts,average_fleet_age,accidents_last_5y
0,Alaska Airlines,US,AS,1.0,2025-01-16T00:00:00.000Z,1.0,158.0,8.1,1.0
1,American Airlines,US,AA,1.0,2025-07-29T00:00:00.000Z,1.0,684.0,10.2,26.0
2,Air Canada,CA,AC,1.0,2024-04-18T00:00:00.000Z,1.0,98.0,11.7,0.0
3,Delta Air Lines,US,DL,1.0,2024-10-17T00:00:00.000Z,1.0,591.0,12.5,22.0
4,Envoy Air,US,MQ,1.0,2025-11-18T00:00:00.000Z,1.0,161.0,9.6,0.0
5,Frontier Airlines,US,F9,1.0,2024-01-03T00:00:00.000Z,1.0,83.0,3.0,4.0
6,GOL Linhas Aereas Inteligentes,BR,G3,1.0,2025-11-23T00:00:00.000Z,1.0,103.0,10.7,0.0
7,Jazz Aviation,CA,QK,1.0,2024-10-21T00:00:00.000Z,1.0,85.0,13.8,3.0
8,Lufthansa Cargo,DE,LH,1.0,2026-02-02T00:00:00.000Z,1.0,15.0,10.7,0.0
9,Lufthansa,DE,LH,1.0,2026-5-12T00:00:00.000Z,1.0,131.0,8.9,1.0
10,Porter Airlines Inc,CA,P3,0.0,NaN,1.0,1.0,8.0,0.0
11,Porter Airlines,CA,PD,0.0,NaN,1.0,1.0,9.0,0.0
12,Republic Airline United Express,US,YX,1.0,2024-12-12T00:00:00.000Z,1.0,182.0,10.1,1.0
13,SkyWest Airlines,US,OO,1.0,2024-09-25T00:00:00.000Z,1.0,462.0,10.7,3.0
14,Spirit Airlines,US,NK,1.0,2025-07-30T00:00:00.000Z,1.0,125.0,4.1,4.0
15,United Airlines,US,UA,1.0,2025-02-26T00:00:00.000Z,1.0,502.0,14.1,12.0
16,Westjet,CA,WS,1.0,2024-11-27T00:00:00.000Z,1.0,70.0,9.8,5.0
17,American Eagle,US,AA,1.0,2024-08-2T00:00:00.000Z,1.0,567.0,10.0,1.0

##### Lufthansa and  Lufthansa Cargo have the same iata code.We are working on passenger flights. Therefore, remove Lufthansa Cargo from the list

In [28]:
# Delete the row where the airline name is Lufthansa Cargo
wanted_airlines = wanted_airlines_fields[wanted_airlines_fields['Name'] != 'Lufthansa Cargo']
wanted_airlines

,Name,country_code,iata_code,iosa_registered,iosa_expiry,is_scheduled,total_aircrafts,average_fleet_age,accidents_last_5y
0,Alaska Airlines,US,AS,1.0,2025-01-16T00:00:00.000Z,1.0,158.0,8.1,1.0
1,American Airlines,US,AA,1.0,2025-07-29T00:00:00.000Z,1.0,684.0,10.2,26.0
2,Air Canada,CA,AC,1.0,2024-04-18T00:00:00.000Z,1.0,98.0,11.7,0.0
3,Delta Air Lines,US,DL,1.0,2024-10-17T00:00:00.000Z,1.0,591.0,12.5,22.0
4,Envoy Air,US,MQ,1.0,2025-11-18T00:00:00.000Z,1.0,161.0,9.6,0.0
5,Frontier Airlines,US,F9,1.0,2024-01-03T00:00:00.000Z,1.0,83.0,3.0,4.0
6,GOL Linhas Aereas Inteligentes,BR,G3,1.0,2025-11-23T00:00:00.000Z,1.0,103.0,10.7,0.0
7,Jazz Aviation,CA,QK,1.0,2024-10-21T00:00:00.000Z,1.0,85.0,13.8,3.0
9,Lufthansa,DE,LH,1.0,2026-5-12T00:00:00.000Z,1.0,131.0,8.9,1.0
10,Porter Airlines Inc,CA,P3,0.0,NaN,1.0,1.0,8.0,0.0
11,Porter Airlines,CA,PD,0.0,NaN,1.0,1.0,9.0,0.0
12,Republic Airline United Express,US,YX,1.0,2024-12-12T00:00:00.000Z,1.0,182.0,10.1,1.0
13,SkyWest Airlines,US,OO,1.0,2024-09-25T00:00:00.000Z,1.0,462.0,10.7,3.0
14,Spirit Airlines,US,NK,1.0,2025-07-30T00:00:00.000Z,1.0,125.0,4.1,4.0
15,United Airlines,US,UA,1.0,2025-02-26T00:00:00.000Z,1.0,502.0,14.1,12.0
16,Westjet,CA,WS,1.0,2024-11-27T00:00:00.000Z,1.0,70.0,9.8,5.0
17,American Eagle,US,AA,1.0,2024-08-2T00:00:00.000Z,1.0,567.0,10.0,1.0

In [29]:
wanted_airlines = wanted_airlines.rename(columns={'Name':'airline_name','iata_code':'iata', 'is_scheduled':'is_airline_passenger'})
wanted_airlines

,airline_name,country_code,iata,iosa_registered,iosa_expiry,is_airline_passenger,total_aircrafts,average_fleet_age,accidents_last_5y
0,Alaska Airlines,US,AS,1.0,2025-01-16T00:00:00.000Z,1.0,158.0,8.1,1.0
1,American Airlines,US,AA,1.0,2025-07-29T00:00:00.000Z,1.0,684.0,10.2,26.0
2,Air Canada,CA,AC,1.0,2024-04-18T00:00:00.000Z,1.0,98.0,11.7,0.0
3,Delta Air Lines,US,DL,1.0,2024-10-17T00:00:00.000Z,1.0,591.0,12.5,22.0
4,Envoy Air,US,MQ,1.0,2025-11-18T00:00:00.000Z,1.0,161.0,9.6,0.0
5,Frontier Airlines,US,F9,1.0,2024-01-03T00:00:00.000Z,1.0,83.0,3.0,4.0
6,GOL Linhas Aereas Inteligentes,BR,G3,1.0,2025-11-23T00:00:00.000Z,1.0,103.0,10.7,0.0
7,Jazz Aviation,CA,QK,1.0,2024-10-21T00:00:00.000Z,1.0,85.0,13.8,3.0
9,Lufthansa,DE,LH,1.0,2026-5-12T00:00:00.000Z,1.0,131.0,8.9,1.0
10,Porter Airlines Inc,CA,P3,0.0,NaN,1.0,1.0,8.0,0.0
11,Porter Airlines,CA,PD,0.0,NaN,1.0,1.0,9.0,0.0
12,Republic Airline United Express,US,YX,1.0,2024-12-12T00:00:00.000Z,1.0,182.0,10.1,1.0
13,SkyWest Airlines,US,OO,1.0,2024-09-25T00:00:00.000Z,1.0,462.0,10.7,3.0
14,Spirit Airlines,US,NK,1.0,2025-07-30T00:00:00.000Z,1.0,125.0,4.1,4.0
15,United Airlines,US,UA,1.0,2025-02-26T00:00:00.000Z,1.0,502.0,14.1,12.0
16,Westjet,CA,WS,1.0,2024-11-27T00:00:00.000Z,1.0,70.0,9.8,5.0
17,American Eagle,US,AA,1.0,2024-08-2T00:00:00.000Z,1.0,567.0,10.0,1.0

In [30]:
# Save the airline file
wanted_airlines.to_csv("extracted_airlines.csv", index=False)

In [ ]:
# Create a mapping dictionary based on the airlines dataset
airline_name_mapping = {
"WestJet" : "Westjet",
"Porter Airlines (Canada) Ltd": "Porter Airlines",
"Delta": "Delta Air Lines" ,
"American Airlines": "American Airlines",
"United":"United Airlines",
"Spirit Airlines": "Spirit Airlines",
"Lufthansa":"Lufthansa",
"Frontier Airlines":"Frontier Airlines",
"Air Canada": "Air Canada",
"Alaska Airlines":"Alaska Airlines",
"GOL Linhas": "GOL Linhas Aereas Inteligentes",
"Porter Airlines Inc": " Porter Airlines Inc",
"Envoy Air As American Eagle": "Envoy Air",
"Republic Airways AS American Eagle": "American Eagle",
"Air Canada Express - Jazz": "Jazz Aviation",
"Republic Airways DBA United Express": "Republic Airline United Express",
"SkyWest DBA United Express": "SkyWest Airlines#"
}

selected_flight_price_data.loc[:, ['marketing_airline', 'operating_airline']] = selected_flight_price_data[['marketing_airline', 'operating_airline']].replace(airline_name_mapping)
selected_flight_price_data

,itinerary_id,cabin_class,price_formatted,flight_number,origin_airport,destination_airport,departure_time,arrival_time,stop_count,marketing_airline,operating_airline,is_self_transfer,score,duration_in_hours
8,18467-2504010745--31679-1-10968-2504011249,economy,C$477,6340,YYZ,ATL,2025-04-01T07:45:00,2025-04-01T10:17:00,1,Westjet,Delta Air Lines,False,0.544887,2.53
9,18467-2504010745--31679-1-10968-2504011249,economy,C$477,6482,ATL,DFW,2025-04-01T11:20:00,2025-04-01T12:49:00,1,Westjet,Delta Air Lines,False,0.544887,2.48
16,"18390-2504010700--31954,-31825-2-10968-2504011735",economy,C$253,2205,YTZ,YOW,2025-04-01T07:00:00,2025-04-01T07:59:00,2,Porter Airlines,Porter Airlines Inc,True,0.462699,0.98
29,18467-2504010615--32385-1-10910-2504011111,premium_economy,C$581,2662,YYZ,ATL,2025-04-01T06:15:00,2025-04-01T08:49:00,1,Delta Air Lines,Delta Air Lines,False,0.576769,2.57
31,18467-2504010745--32385-1-10968-2504011249,premium_economy,C$581,2988,YYZ,ATL,2025-04-01T07:45:00,2025-04-01T10:17:00,1,Delta Air Lines,Delta Air Lines,False,0.565300,2.53
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22112,18467-2509300820--31722-0-10968-2509301042,first,C$846,8169,YYZ,DFW,2025-09-30T08:20:00,2025-09-30T10:42:00,0,United Airlines,Air Canada,False,0.668470,3.37
22113,18467-2509301310--32573-1-10968-2509301744,first,C$582,3606,YYZ,ORD,2025-09-30T13:10:00,2025-09-30T14:05:00,1,American Airlines,Envoy Air,False,0.590065,1.92
22114,18467-2509301310--32573-1-10968-2509301744,first,C$582,2429,ORD,DFW,2025-09-30T15:15:00,2025-09-30T17:44:00,1,American Airlines,American Airlines,False,0.590065,2.48
22127,18467-2509301130--32573-1-10968-2509301841,first,C$582,3604,YYZ,ORD,2025-09-30T11:30:00,2025-09-30T12:25:00,1,American Airlines,Envoy Air,False,0.362377,1.92
22128,18467-2509301130--32573-1-10968-2509301841,first,C$582,1193,ORD,DFW,2025-09-30T16:12:00,2025-09-30T18:41:00,1,American Airlines,American Airlines,False,0.362377,2.48

In [32]:
selected_flight_price_data.rename(columns={'price_formatted':'one_way_price',
                                   'is_self_tansfer':'self_tranfer_allowed'})

,itinerary_id,cabin_class,one_way_price,flight_number,origin_airport,destination_airport,departure_time,arrival_time,stop_count,marketing_airline,operating_airline,is_self_transfer,score,duration_in_hours
8,18467-2504010745--31679-1-10968-2504011249,economy,C$477,6340,YYZ,ATL,2025-04-01T07:45:00,2025-04-01T10:17:00,1,Westjet,Delta Air Lines,False,0.544887,2.53
9,18467-2504010745--31679-1-10968-2504011249,economy,C$477,6482,ATL,DFW,2025-04-01T11:20:00,2025-04-01T12:49:00,1,Westjet,Delta Air Lines,False,0.544887,2.48
16,"18390-2504010700--31954,-31825-2-10968-2504011735",economy,C$253,2205,YTZ,YOW,2025-04-01T07:00:00,2025-04-01T07:59:00,2,Porter Airlines,Porter Airlines Inc,True,0.462699,0.98
29,18467-2504010615--32385-1-10910-2504011111,premium_economy,C$581,2662,YYZ,ATL,2025-04-01T06:15:00,2025-04-01T08:49:00,1,Delta Air Lines,Delta Air Lines,False,0.576769,2.57
31,18467-2504010745--32385-1-10968-2504011249,premium_economy,C$581,2988,YYZ,ATL,2025-04-01T07:45:00,2025-04-01T10:17:00,1,Delta Air Lines,Delta Air Lines,False,0.565300,2.53
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22112,18467-2509300820--31722-0-10968-2509301042,first,C$846,8169,YYZ,DFW,2025-09-30T08:20:00,2025-09-30T10:42:00,0,United Airlines,Air Canada,False,0.668470,3.37
22113,18467-2509301310--32573-1-10968-2509301744,first,C$582,3606,YYZ,ORD,2025-09-30T13:10:00,2025-09-30T14:05:00,1,American Airlines,Envoy Air,False,0.590065,1.92
22114,18467-2509301310--32573-1-10968-2509301744,first,C$582,2429,ORD,DFW,2025-09-30T15:15:00,2025-09-30T17:44:00,1,American Airlines,American Airlines,False,0.590065,2.48
22127,18467-2509301130--32573-1-10968-2509301841,first,C$582,3604,YYZ,ORD,2025-09-30T11:30:00,2025-09-30T12:25:00,1,American Airlines,Envoy Air,False,0.362377,1.92
22128,18467-2509301130--32573-1-10968-2509301841,first,C$582,1193,ORD,DFW,2025-09-30T16:12:00,2025-09-30T18:41:00,1,American Airlines,American Airlines,False,0.362377,2.48

# Understanding flight_price_full_year_df

In [33]:
# Display first few rows of the combined dataframe
selected_flight_price_data.head()

,itinerary_id,cabin_class,price_formatted,flight_number,origin_airport,destination_airport,departure_time,arrival_time,stop_count,marketing_airline,operating_airline,is_self_transfer,score,duration_in_hours
8,18467-2504010745--31679-1-10968-2504011249,economy,C$477,6340,YYZ,ATL,2025-04-01T07:45:00,2025-04-01T10:17:00,1,Westjet,Delta Air Lines,False,0.544887,2.53
9,18467-2504010745--31679-1-10968-2504011249,economy,C$477,6482,ATL,DFW,2025-04-01T11:20:00,2025-04-01T12:49:00,1,Westjet,Delta Air Lines,False,0.544887,2.48
16,"18390-2504010700--31954,-31825-2-10968-2504011735",economy,C$253,2205,YTZ,YOW,2025-04-01T07:00:00,2025-04-01T07:59:00,2,Porter Airlines,Porter Airlines Inc,True,0.462699,0.98
29,18467-2504010615--32385-1-10910-2504011111,premium_economy,C$581,2662,YYZ,ATL,2025-04-01T06:15:00,2025-04-01T08:49:00,1,Delta Air Lines,Delta Air Lines,False,0.576769,2.57
31,18467-2504010745--32385-1-10968-2504011249,premium_economy,C$581,2988,YYZ,ATL,2025-04-01T07:45:00,2025-04-01T10:17:00,1,Delta Air Lines,Delta Air Lines,False,0.565300,2.53

In [34]:
# Retrieve all information about the flight price dataset
selected_flight_price_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11127 entries, 8 to 22128
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   itinerary_id         11127 non-null  object
 1   cabin_class          11127 non-null  object
 2   price_formatted      11127 non-null  object
 3   flight_number        11127 non-null  int64
 4   origin_airport       11127 non-null  object
 5   destination_airport  11127 non-null  object
 6   departure_time       11127 non-null  object
 7   arrival_time         11127 non-null  object
 8   stop_count           11127 non-null  int64
 9   marketing_airline    11127 non-null  object
 10  operating_airline    11127 non-null  object
 11  is_self_transfer     11127 non-null  bool
 12  score                11127 non-null  float64
 13  duration_in_hours    11127 non-null  float64
dtypes: bool(1), float64(2), int64(2), object(9)
memory usage: 1.2+ MB

In [35]:
selected_flight_price_data.describe()

       flight_number    stop_count         score  duration_in_hours
count   11127.000000  11127.000000  11127.000000       11127.000000
mean     3187.528444      0.776849      0.537798           2.632175
std      2440.465516      0.507973      0.227394           0.670955
min        31.000000      0.000000      0.055562           0.980000
25%      1111.000000      0.000000      0.364917           2.250000
50%      2710.000000      1.000000      0.484336           2.420000
75%      4238.000000      1.000000      0.660007           3.330000
max      8909.000000      4.000000      0.999530           5.670000

In [36]:
# Check for missing values
selected_flight_price_data.isnull().sum()

itinerary_id           0
cabin_class            0
price_formatted        0
flight_number          0
origin_airport         0
destination_airport    0
departure_time         0
arrival_time           0
stop_count             0
marketing_airline      0
operating_airline      0
is_self_transfer       0
score                  0
duration_in_hours      0
dtype: int64

In [37]:
selected_flight_price_data.reset_index()

,index,itinerary_id,cabin_class,price_formatted,flight_number,origin_airport,destination_airport,departure_time,arrival_time,stop_count,marketing_airline,operating_airline,is_self_transfer,score,duration_in_hours
0,8,18467-2504010745--31679-1-10968-2504011249,economy,C$477,6340,YYZ,ATL,2025-04-01T07:45:00,2025-04-01T10:17:00,1,Westjet,Delta Air Lines,False,0.544887,2.53
1,9,18467-2504010745--31679-1-10968-2504011249,economy,C$477,6482,ATL,DFW,2025-04-01T11:20:00,2025-04-01T12:49:00,1,Westjet,Delta Air Lines,False,0.544887,2.48
2,16,"18390-2504010700--31954,-31825-2-10968-2504011735",economy,C$253,2205,YTZ,YOW,2025-04-01T07:00:00,2025-04-01T07:59:00,2,Porter Airlines,Porter Airlines Inc,True,0.462699,0.98
3,29,18467-2504010615--32385-1-10910-2504011111,premium_economy,C$581,2662,YYZ,ATL,2025-04-01T06:15:00,2025-04-01T08:49:00,1,Delta Air Lines,Delta Air Lines,False,0.576769,2.57
4,31,18467-2504010745--32385-1-10968-2504011249,premium_economy,C$581,2988,YYZ,ATL,2025-04-01T07:45:00,2025-04-01T10:17:00,1,Delta Air Lines,Delta Air Lines,False,0.565300,2.53
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11122,22112,18467-2509300820--31722-0-10968-2509301042,first,C$846,8169,YYZ,DFW,2025-09-30T08:20:00,2025-09-30T10:42:00,0,United Airlines,Air Canada,False,0.668470,3.37
11123,22113,18467-2509301310--32573-1-10968-2509301744,first,C$582,3606,YYZ,ORD,2025-09-30T13:10:00,2025-09-30T14:05:00,1,American Airlines,Envoy Air,False,0.590065,1.92
11124,22114,18467-2509301310--32573-1-10968-2509301744,first,C$582,2429,ORD,DFW,2025-09-30T15:15:00,2025-09-30T17:44:00,1,American Airlines,American Airlines,False,0.590065,2.48
11125,22127,18467-2509301130--32573-1-10968-2509301841,first,C$582,3604,YYZ,ORD,2025-09-30T11:30:00,2025-09-30T12:25:00,1,American Airlines,Envoy Air,False,0.362377,1.92
11126,22128,18467-2509301130--32573-1-10968-2509301841,first,C$582,1193,ORD,DFW,2025-09-30T16:12:00,2025-09-30T18:41:00,1,American Airlines,American Airlines,False,0.362377,2.48

In [38]:
selected_flight_price_data.to_csv ('extracted_price_data.csv', index = False, header=True)