In [107]:
import pandas as pd
import numpy as np

# Creating DataFrame for itinerary. Here itinerary_id is the primary key.

In [108]:
flight_price_data =  pd.read_csv('cleaned_price_data.csv')
flight_price_data

,itinerary_id,cabin_class,one_way_price_candollar,flight_number,origin_airport,destination_airport,departure_date_time,arrival_date_time,stop_count,marketing_airline,operating_airline,is_self_transfer,score,duration_in_hours
0,18467-2504010745--31679-1-10968-2504011249,economy,477,6340,YYZ,ATL,2025-04-01 07:45:00,2025-04-01 10:17:00,1,Westjet,Delta Air Lines,True,0.544887,2.53
1,18467-2504010745--31679-1-10968-2504011249,economy,477,6482,ATL,DFW,2025-04-01 11:20:00,2025-04-01 12:49:00,1,Westjet,Delta Air Lines,True,0.544887,2.48
2,"18390-2504010700--31954,-31825-2-10968-2504011735",economy,253,2205,YTZ,YOW,2025-04-01 07:00:00,2025-04-01 07:59:00,2,Porter Airlines,Porter Airlines Inc,True,0.462699,0.98
3,18467-2504010615--32385-1-10910-2504011111,premium_economy,581,2662,YYZ,ATL,2025-04-01 06:15:00,2025-04-01 08:49:00,1,Delta Air Lines,Delta Air Lines,True,0.576769,2.57
4,18467-2504010745--32385-1-10968-2504011249,premium_economy,581,2988,YYZ,ATL,2025-04-01 07:45:00,2025-04-01 10:17:00,1,Delta Air Lines,Delta Air Lines,True,0.565300,2.53
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11122,18467-2509300820--31722-0-10968-2509301042,first,846,8169,YYZ,DFW,2025-09-30 08:20:00,2025-09-30 10:42:00,0,United Airlines,Air Canada,True,0.668470,3.37
11123,18467-2509301310--32573-1-10968-2509301744,first,582,3606,YYZ,ORD,2025-09-30 13:10:00,2025-09-30 14:05:00,1,American Airlines,Envoy Air,True,0.590065,1.92
11124,18467-2509301310--32573-1-10968-2509301744,first,582,2429,ORD,DFW,2025-09-30 15:15:00,2025-09-30 17:44:00,1,American Airlines,American Airlines,True,0.590065,2.48
11125,18467-2509301130--32573-1-10968-2509301841,first,582,3604,YYZ,ORD,2025-09-30 11:30:00,2025-09-30 12:25:00,1,American Airlines,Envoy Air,True,0.362377,1.92
11126,18467-2509301130--32573-1-10968-2509301841,first,582,1193,ORD,DFW,2025-09-30 16:12:00,2025-09-30 18:41:00,1,American Airlines,American Airlines,True,0.362377,2.48

In [109]:
flight_price_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11127 entries, 0 to 11126
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   itinerary_id             11127 non-null  object
 1   cabin_class              11127 non-null  object
 2   one_way_price_candollar  11127 non-null  int64
 3   flight_number            11127 non-null  int64
 4   origin_airport           11127 non-null  object
 5   destination_airport      11127 non-null  object
 6   departure_date_time      11127 non-null  object
 7   arrival_date_time        11127 non-null  object
 8   stop_count               11127 non-null  int64
 9   marketing_airline        11127 non-null  object
 10  operating_airline        11127 non-null  object
 11  is_self_transfer         11127 non-null  bool
 12  score                    11127 non-null  float64
 13  duration_in_hours        11127 non-null  float64
dtypes: bool(1), float64(2), int64(3), object(8)
memory usage: 1.1+ MB

##### Extracting unique itinerary_id from  flight_price_data

In [110]:
unique_itineraries = flight_price_data['itinerary_id'].unique()
unique_itineraries

array(['18467-2504010745--31679-1-10968-2504011249',
       '18390-2504010700--31954,-31825-2-10968-2504011735',
       '18467-2504010615--32385-1-10910-2504011111', ...,
       '18467-2509301635--31722-0-10968-2509301857',
       '18467-2509300820--31722-0-10968-2509301042',
       '18467-2509301130--32573-1-10968-2509301841'], dtype=object)

In [111]:
# Create a DataFrame
itinerary_df = pd.DataFrame({"itineraries": unique_itineraries})
itinerary_df
# Add a new column with sequential labels ('it1', 'it2', ...)
itinerary_df['itinerary_id'] = [f"it{i+1}" for i in range(len(itinerary_df))]
itinerary_df = itinerary_df[['itinerary_id','itineraries']]
itinerary_df

     itinerary_id                                        itineraries
0             it1         18467-2504010745--31679-1-10968-2504011249
1             it2  18390-2504010700--31954,-31825-2-10968-2504011735
2             it3         18467-2504010615--32385-1-10910-2504011111
3             it4         18467-2504010745--32385-1-10968-2504011249
4             it5         18467-2504011220--32385-1-10910-2504011753
...           ...                                                ...
6322       it6323         18467-2509301320--32385-1-10968-2509301833
6323       it6324         18467-2509301130--32385-1-10968-2509301647
6324       it6325         18467-2509301635--31722-0-10968-2509301857
6325       it6326         18467-2509300820--31722-0-10968-2509301042
6326       it6327         18467-2509301130--32573-1-10968-2509301841

[6327 rows x 2 columns]

In [112]:
itinerary_df.to_csv('itinerary.csv', index=False)

In [113]:
itinerary_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6327 entries, 0 to 6326
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   itinerary_id  6327 non-null   object
 1   itineraries   6327 non-null   object
dtypes: object(2)
memory usage: 99.0+ KB

# Creating dataframe for cabin_class.Here cabin_class_id is the primary key.

##### Extracting unique cabin classes from the cabin_class column of flight_price_data

In [114]:
unique_cabin_classes = flight_price_data['cabin_class'].unique()
unique_cabin_classes

array(['economy', 'premium_economy', 'business', 'first'], dtype=object)

In [115]:
# Create a DataFrame
unique_cabin_classes_df = pd.DataFrame({"cabin_class": unique_cabin_classes})
unique_cabin_classes_df
# Add a new column with sequential labels ('cc1', 'cc2', ...)
unique_cabin_classes_df['cabin_class_id'] = [f"cc{i+1}" for i in range(len(unique_cabin_classes_df))]
unique_cabin_classes_df = unique_cabin_classes_df[['cabin_class_id','cabin_class']]
unique_cabin_classes_df

  cabin_class_id      cabin_class
0            cc1          economy
1            cc2  premium_economy
2            cc3         business
3            cc4            first

In [116]:
unique_cabin_classes_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   cabin_class_id  4 non-null      object
 1   cabin_class     4 non-null      object
dtypes: object(2)
memory usage: 192.0+ bytes

In [117]:
unique_cabin_classes_df.to_csv('cabin_class.csv', index=False)

# Creating dataframe for airports. Here iata code is the primary key

In [118]:
airports_df = pd.read_csv('cleaned_extracted_airports.csv')
airports_df

,name,iata code,country,city,latitude,longitude,timezone,departures
0,Billy Bishop Toronto City Airport,YTZ,CA,Toronto,752.0,-79.39828,EST,752
1,Kitchener/Waterloo Airport,YKF,CA,Breslau,454.0,-80.38593,EST,454
2,Montreal-Pierre Elliott Trudeau International ...,YUL,CA,Montreal,35190.0,-73.75019,EST,35190
3,Ottawa Macdonald-Cartier International Airport,YOW,CA,Ottawa,10293.0,-75.66917,EST,10293
4,Toronto Pearson International Airport,YYZ,CA,Toronto,72355.0,-79.61286,EST,72355
5,Chicago O'Hare International Airport,ORD,US,Chicago,177167.0,-87.90446,CST,177167
6,Dallas/Fort Worth International Airport,DFW,US,Dallas-Ft Worth,172447.0,-97.03720,CST,172447
7,Denver International Airport,DEN,US,Denver,100565.0,-104.67326,MST,100565
8,Hartsfield-Jackson Atlanta International Airport,ATL,US,Atlanta,168164.0,-84.42265,EST,168164
9,Los Angeles International Airport,LAX,US,Los Angeles,112571.0,-118.40897,PST,112571

In [119]:
airports_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        10 non-null     object
 1   iata code   10 non-null     object
 2   country     10 non-null     object
 3   city        10 non-null     object
 4   latitude    10 non-null     float64
 5   longitude   10 non-null     float64
 6   timezone    10 non-null     object
 7   departures  10 non-null     int64
dtypes: float64(2), int64(1), object(5)
memory usage: 768.0+ bytes

In [120]:
# Add airline_id as an index-based unique identifier
airports_df['airport_id'] = [f"ap{i+1}" for i in range(len(airports_df))]
airports_df

,name,iata code,country,city,latitude,longitude,timezone,departures,airport_id
0,Billy Bishop Toronto City Airport,YTZ,CA,Toronto,752.0,-79.39828,EST,752,ap1
1,Kitchener/Waterloo Airport,YKF,CA,Breslau,454.0,-80.38593,EST,454,ap2
2,Montreal-Pierre Elliott Trudeau International ...,YUL,CA,Montreal,35190.0,-73.75019,EST,35190,ap3
3,Ottawa Macdonald-Cartier International Airport,YOW,CA,Ottawa,10293.0,-75.66917,EST,10293,ap4
4,Toronto Pearson International Airport,YYZ,CA,Toronto,72355.0,-79.61286,EST,72355,ap5
5,Chicago O'Hare International Airport,ORD,US,Chicago,177167.0,-87.90446,CST,177167,ap6
6,Dallas/Fort Worth International Airport,DFW,US,Dallas-Ft Worth,172447.0,-97.03720,CST,172447,ap7
7,Denver International Airport,DEN,US,Denver,100565.0,-104.67326,MST,100565,ap8
8,Hartsfield-Jackson Atlanta International Airport,ATL,US,Atlanta,168164.0,-84.42265,EST,168164,ap9
9,Los Angeles International Airport,LAX,US,Los Angeles,112571.0,-118.40897,PST,112571,ap10

In [121]:
airports_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        10 non-null     object
 1   iata code   10 non-null     object
 2   country     10 non-null     object
 3   city        10 non-null     object
 4   latitude    10 non-null     float64
 5   longitude   10 non-null     float64
 6   timezone    10 non-null     object
 7   departures  10 non-null     int64
 8   airport_id  10 non-null     object
dtypes: float64(2), int64(1), object(6)
memory usage: 848.0+ bytes

In [122]:
airports_df.to_csv('airports.csv',index=False)

# Creating dataframe for airlines. Here airline_id is the primary key.

In [123]:
airlines_df =  pd.read_csv('cleaned_extracted_airlines.csv')

In [124]:
airlines_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   airline_name          17 non-null     object
 1   country_code          17 non-null     object
 2   iata                  17 non-null     object
 3   iosa_registered       17 non-null     bool
 4   iosa_expiry           15 non-null     object
 5   is_airline_passenger  17 non-null     bool
 6   total_aircrafts       17 non-null     int64
 7   average_fleet_age     17 non-null     float64
 8   accidents_last_5y     17 non-null     int64
dtypes: bool(2), float64(1), int64(2), object(4)
memory usage: 1.1+ KB

In [125]:
# Convert to datetime
airlines_df['iosa_expiry'] = pd.to_datetime(airlines_df['iosa_expiry'], errors='coerce')
# Fill missing value with NAT 
airlines_df['iosa_expiry'] = airlines_df['iosa_expiry'].fillna(pd.NaT)

In [126]:
airlines_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   airline_name          17 non-null     object
 1   country_code          17 non-null     object
 2   iata                  17 non-null     object
 3   iosa_registered       17 non-null     bool
 4   iosa_expiry           15 non-null     datetime64[ns, UTC]
 5   is_airline_passenger  17 non-null     bool
 6   total_aircrafts       17 non-null     int64
 7   average_fleet_age     17 non-null     float64
 8   accidents_last_5y     17 non-null     int64
dtypes: bool(2), datetime64[ns, UTC](1), float64(1), int64(2), object(3)
memory usage: 1.1+ KB

In [127]:
# Add airline_id as an index-based unique identifier
airlines_df['airline_id'] = [f"al{i+1}" for i in range(len(airlines_df))]

airlines_df

,airline_name,country_code,iata,iosa_registered,iosa_expiry,is_airline_passenger,total_aircrafts,average_fleet_age,accidents_last_5y,airline_id
0,Alaska Airlines,US,AS,True,2025-01-16 00:00:00+00:00,True,158,8.1,1,al1
1,American Airlines,US,AA,True,2025-07-29 00:00:00+00:00,True,684,10.2,26,al2
2,Air Canada,CA,AC,True,2024-04-18 00:00:00+00:00,True,98,11.7,0,al3
3,Delta Air Lines,US,DL,True,2024-10-17 00:00:00+00:00,True,591,12.5,22,al4
4,Envoy Air,US,MQ,True,2025-11-18 00:00:00+00:00,True,161,9.6,0,al5
5,Frontier Airlines,US,F9,True,2024-01-03 00:00:00+00:00,True,83,3.0,4,al6
6,GOL Linhas Aereas Inteligentes,BR,G3,True,2025-11-23 00:00:00+00:00,True,103,10.7,0,al7
7,Jazz Aviation,CA,QK,True,2024-10-21 00:00:00+00:00,True,85,13.8,3,al8
8,Lufthansa,DE,LH,True,2026-05-12 00:00:00+00:00,True,131,8.9,1,al9
9,Porter Airlines Inc,CA,P3,True,NaT,True,1,8.0,0,al10
10,Porter Airlines,CA,PD,True,NaT,True,1,9.0,0,al11
11,Republic Airline United Express,US,YX,True,2024-12-12 00:00:00+00:00,True,182,10.1,1,al12
12,SkyWest Airlines,US,OO,True,2024-09-25 00:00:00+00:00,True,462,10.7,3,al13
13,Spirit Airlines,US,NK,True,2025-07-30 00:00:00+00:00,True,125,4.1,4,al14
14,United Airlines,US,UA,True,2025-02-26 00:00:00+00:00,True,502,14.1,12,al15
15,Westjet,CA,WS,True,2024-11-27 00:00:00+00:00,True,70,9.8,5,al16
16,American Eagle,US,AA,True,2024-08-02 00:00:00+00:00,True,567,10.0,1,al17

In [128]:
airlines_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   airline_name          17 non-null     object
 1   country_code          17 non-null     object
 2   iata                  17 non-null     object
 3   iosa_registered       17 non-null     bool
 4   iosa_expiry           15 non-null     datetime64[ns, UTC]
 5   is_airline_passenger  17 non-null     bool
 6   total_aircrafts       17 non-null     int64
 7   average_fleet_age     17 non-null     float64
 8   accidents_last_5y     17 non-null     int64
 9   airline_id            17 non-null     object
dtypes: bool(2), datetime64[ns, UTC](1), float64(1), int64(2), object(4)
memory usage: 1.2+ KB

In [129]:
# Reorder the columns
airlines_df=airlines_df[['airline_id','airline_name','iata','country_code','is_airline_passenger','total_aircrafts','average_fleet_age','accidents_last_5y','iosa_registered','iosa_expiry']]
airlines_df

,airline_id,airline_name,iata,country_code,is_airline_passenger,total_aircrafts,average_fleet_age,accidents_last_5y,iosa_registered,iosa_expiry
0,al1,Alaska Airlines,AS,US,True,158,8.1,1,True,2025-01-16 00:00:00+00:00
1,al2,American Airlines,AA,US,True,684,10.2,26,True,2025-07-29 00:00:00+00:00
2,al3,Air Canada,AC,CA,True,98,11.7,0,True,2024-04-18 00:00:00+00:00
3,al4,Delta Air Lines,DL,US,True,591,12.5,22,True,2024-10-17 00:00:00+00:00
4,al5,Envoy Air,MQ,US,True,161,9.6,0,True,2025-11-18 00:00:00+00:00
5,al6,Frontier Airlines,F9,US,True,83,3.0,4,True,2024-01-03 00:00:00+00:00
6,al7,GOL Linhas Aereas Inteligentes,G3,BR,True,103,10.7,0,True,2025-11-23 00:00:00+00:00
7,al8,Jazz Aviation,QK,CA,True,85,13.8,3,True,2024-10-21 00:00:00+00:00
8,al9,Lufthansa,LH,DE,True,131,8.9,1,True,2026-05-12 00:00:00+00:00
9,al10,Porter Airlines Inc,P3,CA,True,1,8.0,0,True,NaT
10,al11,Porter Airlines,PD,CA,True,1,9.0,0,True,NaT
11,al12,Republic Airline United Express,YX,US,True,182,10.1,1,True,2024-12-12 00:00:00+00:00
12,al13,SkyWest Airlines,OO,US,True,462,10.7,3,True,2024-09-25 00:00:00+00:00
13,al14,Spirit Airlines,NK,US,True,125,4.1,4,True,2025-07-30 00:00:00+00:00
14,al15,United Airlines,UA,US,True,502,14.1,12,True,2025-02-26 00:00:00+00:00
15,al16,Westjet,WS,CA,True,70,9.8,5,True,2024-11-27 00:00:00+00:00
16,al17,American Eagle,AA,US,True,567,10.0,1,True,2024-08-02 00:00:00+00:00

In [130]:
airlines_df.to_csv('airlines.csv',index=False)

# Creating dataframe for country_code. Here country_id is the primary key.

In [131]:
unique_country_code = airlines_df['country_code'].unique()
unique_country_code

array(['US', 'CA', 'BR', 'DE'], dtype=object)

In [132]:
# Create a DataFrame
unique_country_code = pd.DataFrame({"country_code": unique_country_code})
unique_country_code
# Add a new column with sequential labels ('cc1', 'cc2', ...)
unique_country_code['country_code_id'] = [f"coc{i+1}" for i in range(len(unique_country_code))]
unique_country_code = unique_country_code[['country_code_id','country_code']]
unique_country_code

  country_code_id country_code
0            coc1           US
1            coc2           CA
2            coc3           BR
3            coc4           DE

In [133]:
unique_country_code.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   country_code_id  4 non-null      object
 1   country_code     4 non-null      object
dtypes: object(2)
memory usage: 192.0+ bytes

In [134]:
unique_country_code.to_csv('country_code.csv',index=False)

# Creating dataframe for itinerary_details. Here detail_id is the foreign key to the itinerary id

In [135]:
itinerary_details_df = flight_price_data[['itinerary_id','departure_date_time','arrival_date_time','origin_airport','destination_airport','is_self_transfer','flight_number']]
itinerary_details_df

,itinerary_id,departure_date_time,arrival_date_time,origin_airport,destination_airport,is_self_transfer,flight_number
0,18467-2504010745--31679-1-10968-2504011249,2025-04-01 07:45:00,2025-04-01 10:17:00,YYZ,ATL,True,6340
1,18467-2504010745--31679-1-10968-2504011249,2025-04-01 11:20:00,2025-04-01 12:49:00,ATL,DFW,True,6482
2,"18390-2504010700--31954,-31825-2-10968-2504011735",2025-04-01 07:00:00,2025-04-01 07:59:00,YTZ,YOW,True,2205
3,18467-2504010615--32385-1-10910-2504011111,2025-04-01 06:15:00,2025-04-01 08:49:00,YYZ,ATL,True,2662
4,18467-2504010745--32385-1-10968-2504011249,2025-04-01 07:45:00,2025-04-01 10:17:00,YYZ,ATL,True,2988
...,...,...,...,...,...,...,...
11122,18467-2509300820--31722-0-10968-2509301042,2025-09-30 08:20:00,2025-09-30 10:42:00,YYZ,DFW,True,8169
11123,18467-2509301310--32573-1-10968-2509301744,2025-09-30 13:10:00,2025-09-30 14:05:00,YYZ,ORD,True,3606
11124,18467-2509301310--32573-1-10968-2509301744,2025-09-30 15:15:00,2025-09-30 17:44:00,ORD,DFW,True,2429
11125,18467-2509301130--32573-1-10968-2509301841,2025-09-30 11:30:00,2025-09-30 12:25:00,YYZ,ORD,True,3604
11126,18467-2509301130--32573-1-10968-2509301841,2025-09-30 16:12:00,2025-09-30 18:41:00,ORD,DFW,True,1193

##### Reordering columns

In [136]:

itinerary_details_df=itinerary_details_df[['itinerary_id','flight_number','origin_airport','destination_airport','departure_date_time','arrival_date_time','is_self_transfer']]

itinerary_details_df

,itinerary_id,flight_number,origin_airport,destination_airport,departure_date_time,arrival_date_time,is_self_transfer
0,18467-2504010745--31679-1-10968-2504011249,6340,YYZ,ATL,2025-04-01 07:45:00,2025-04-01 10:17:00,True
1,18467-2504010745--31679-1-10968-2504011249,6482,ATL,DFW,2025-04-01 11:20:00,2025-04-01 12:49:00,True
2,"18390-2504010700--31954,-31825-2-10968-2504011735",2205,YTZ,YOW,2025-04-01 07:00:00,2025-04-01 07:59:00,True
3,18467-2504010615--32385-1-10910-2504011111,2662,YYZ,ATL,2025-04-01 06:15:00,2025-04-01 08:49:00,True
4,18467-2504010745--32385-1-10968-2504011249,2988,YYZ,ATL,2025-04-01 07:45:00,2025-04-01 10:17:00,True
...,...,...,...,...,...,...,...
11122,18467-2509300820--31722-0-10968-2509301042,8169,YYZ,DFW,2025-09-30 08:20:00,2025-09-30 10:42:00,True
11123,18467-2509301310--32573-1-10968-2509301744,3606,YYZ,ORD,2025-09-30 13:10:00,2025-09-30 14:05:00,True
11124,18467-2509301310--32573-1-10968-2509301744,2429,ORD,DFW,2025-09-30 15:15:00,2025-09-30 17:44:00,True
11125,18467-2509301130--32573-1-10968-2509301841,3604,YYZ,ORD,2025-09-30 11:30:00,2025-09-30 12:25:00,True
11126,18467-2509301130--32573-1-10968-2509301841,1193,ORD,DFW,2025-09-30 16:12:00,2025-09-30 18:41:00,True

In [137]:
itinerary_details_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11127 entries, 0 to 11126
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   itinerary_id         11127 non-null  object
 1   flight_number        11127 non-null  int64
 2   origin_airport       11127 non-null  object
 3   destination_airport  11127 non-null  object
 4   departure_date_time  11127 non-null  object
 5   arrival_date_time    11127 non-null  object
 6   is_self_transfer     11127 non-null  bool
dtypes: bool(1), int64(1), object(5)
memory usage: 532.6+ KB

In [138]:
itinerary_details_df['departure_date_time']=pd.to_datetime(itinerary_details_df['departure_date_time'], errors='coerce')

In [139]:
itinerary_details_df['arrival_date_time']=pd.to_datetime(itinerary_details_df['arrival_date_time'], errors='coerce')

In [140]:
itinerary_details_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11127 entries, 0 to 11126
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   itinerary_id         11127 non-null  object
 1   flight_number        11127 non-null  int64
 2   origin_airport       11127 non-null  object
 3   destination_airport  11127 non-null  object
 4   departure_date_time  11127 non-null  datetime64[ns]
 5   arrival_date_time    11127 non-null  datetime64[ns]
 6   is_self_transfer     11127 non-null  bool
dtypes: bool(1), datetime64[ns](2), int64(1), object(3)
memory usage: 532.6+ KB

In [141]:
itinerary_details_df.to_csv('itinerary_details.csv',index=False)

# Creating dataframe for flight numbers.Here flight_id is the foreign key to the itinerary_id.

In [142]:
unique_flights = itinerary_details_df['flight_number'].unique()
unique_flights

array([6340, 6482, 2205, 2662, 2988,  414, 2835, 3993, 1111, 1169, 8019,
       8130, 4731, 2257, 3524,  481, 3608,  550,  611,  921, 1538,  307,
       1109, 2714,  818, 8135, 6768, 6499, 2499, 3606, 7789, 6498,  374,
       8533, 3449, 5578, 2290, 1031, 1033, 4476, 4408, 4854, 4990, 5521,
        894, 8813, 5143, 4888, 5634, 3610, 2281,  598, 6536, 5141, 5186,
       8901, 3658, 2259, 2217, 2710, 3604,  436, 7106, 8720, 8742, 2249,
        505, 4235, 7129, 4902, 3371, 6502,  420, 7968, 5137, 5481, 2219,
       2461,  920,  961, 1993, 8156, 8169, 1491, 3499,  490, 1297, 3605,
        793, 1290, 1555, 8080, 1029,  507,  503, 3132, 8903, 1071, 1053,
       3078, 5588, 8909, 4770, 2346,   31, 4530, 8779, 6999, 6479, 6931,
       8278, 2421, 8078, 3170, 3297, 1239, 2999,  501, 1893, 3102, 1401,
       1914, 2862, 2868, 1213, 2247, 1961, 1390, 1642,  416, 2483, 2473,
       2463, 2459, 2485, 4238, 2156, 1841, 2536, 1362, 8307, 3444, 3489,
        516, 8085, 2364, 8694, 1193, 1371, 1856, 8600, 6330, 6980, 1102,
       8497, 7992, 8794, 1041, 3676, 2124, 3093, 5783,  418, 7916,  932,
       1559, 2839,  157,  163, 2333, 3542, 5345, 2201, 4246, 6176, 5697,
       2684, 2565, 3611,  663, 3212, 3241, 1175, 1044, 3529, 3064, 8535,
       8538, 6638, 2451, 2079, 2221, 1777, 2429, 3142], dtype=int64)

In [143]:

# Create a DataFrame properly
unique_flights_df = pd.DataFrame({"flight_number": unique_flights})

# Add a new column with sequential labels ('fl1', 'fl2', ...)
unique_flights_df['flight_id'] = [f"{i+1}" for i in range(len(unique_flights_df))]
# Reorder columns
unique_flights_df = unique_flights_df[['flight_id','flight_number']]
unique_flights_df['flight_id'] = unique_flights_df['flight_id'].astype('int64')

In [144]:
unique_flights_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   flight_id      195 non-null    int64
 1   flight_number  195 non-null    int64
dtypes: int64(2)
memory usage: 3.2 KB

In [145]:
unique_flights_df.to_csv('unique_flights.csv',index=False)

# Creating flight price dataframe. Here price_id is the foreign key to itinerary_id.

In [146]:
flight_price_df = flight_price_data[['itinerary_id','marketing_airline','operating_airline','cabin_class','stop_count','duration_in_hours','one_way_price_candollar']]
flight_price_df

,itinerary_id,marketing_airline,operating_airline,cabin_class,stop_count,duration_in_hours,one_way_price_candollar
0,18467-2504010745--31679-1-10968-2504011249,Westjet,Delta Air Lines,economy,1,2.53,477
1,18467-2504010745--31679-1-10968-2504011249,Westjet,Delta Air Lines,economy,1,2.48,477
2,"18390-2504010700--31954,-31825-2-10968-2504011735",Porter Airlines,Porter Airlines Inc,economy,2,0.98,253
3,18467-2504010615--32385-1-10910-2504011111,Delta Air Lines,Delta Air Lines,premium_economy,1,2.57,581
4,18467-2504010745--32385-1-10968-2504011249,Delta Air Lines,Delta Air Lines,premium_economy,1,2.53,581
...,...,...,...,...,...,...,...
11122,18467-2509300820--31722-0-10968-2509301042,United Airlines,Air Canada,first,0,3.37,846
11123,18467-2509301310--32573-1-10968-2509301744,American Airlines,Envoy Air,first,1,1.92,582
11124,18467-2509301310--32573-1-10968-2509301744,American Airlines,American Airlines,first,1,2.48,582
11125,18467-2509301130--32573-1-10968-2509301841,American Airlines,Envoy Air,first,1,1.92,582
11126,18467-2509301130--32573-1-10968-2509301841,American Airlines,American Airlines,first,1,2.48,582

In [147]:
flight_price_df=flight_price_df[['itinerary_id','cabin_class','stop_count','duration_in_hours','one_way_price_candollar','marketing_airline','operating_airline']]

flight_price_df

,itinerary_id,cabin_class,stop_count,duration_in_hours,one_way_price_candollar,marketing_airline,operating_airline
0,18467-2504010745--31679-1-10968-2504011249,economy,1,2.53,477,Westjet,Delta Air Lines
1,18467-2504010745--31679-1-10968-2504011249,economy,1,2.48,477,Westjet,Delta Air Lines
2,"18390-2504010700--31954,-31825-2-10968-2504011735",economy,2,0.98,253,Porter Airlines,Porter Airlines Inc
3,18467-2504010615--32385-1-10910-2504011111,premium_economy,1,2.57,581,Delta Air Lines,Delta Air Lines
4,18467-2504010745--32385-1-10968-2504011249,premium_economy,1,2.53,581,Delta Air Lines,Delta Air Lines
...,...,...,...,...,...,...,...
11122,18467-2509300820--31722-0-10968-2509301042,first,0,3.37,846,United Airlines,Air Canada
11123,18467-2509301310--32573-1-10968-2509301744,first,1,1.92,582,American Airlines,Envoy Air
11124,18467-2509301310--32573-1-10968-2509301744,first,1,2.48,582,American Airlines,American Airlines
11125,18467-2509301130--32573-1-10968-2509301841,first,1,1.92,582,American Airlines,Envoy Air
11126,18467-2509301130--32573-1-10968-2509301841,first,1,2.48,582,American Airlines,American Airlines

In [148]:
flight_price_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11127 entries, 0 to 11126
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   itinerary_id             11127 non-null  object
 1   cabin_class              11127 non-null  object
 2   stop_count               11127 non-null  int64
 3   duration_in_hours        11127 non-null  float64
 4   one_way_price_candollar  11127 non-null  int64
 5   marketing_airline        11127 non-null  object
 6   operating_airline        11127 non-null  object
dtypes: float64(1), int64(2), object(4)
memory usage: 608.6+ KB

In [149]:
flight_price_df.to_csv('flight_price.csv', index=False)

# Merging cabin_class with flight_price_data

In [150]:
class_flight_price_df = pd.merge(unique_cabin_classes_df,flight_price_data, on='cabin_class')
class_flight_price_df

,cabin_class_id,cabin_class,itinerary_id,one_way_price_candollar,flight_number,origin_airport,destination_airport,departure_date_time,arrival_date_time,stop_count,marketing_airline,operating_airline,is_self_transfer,score,duration_in_hours
0,cc1,economy,18467-2504010745--31679-1-10968-2504011249,477,6340,YYZ,ATL,2025-04-01 07:45:00,2025-04-01 10:17:00,1,Westjet,Delta Air Lines,True,0.544887,2.53
1,cc1,economy,18467-2504010745--31679-1-10968-2504011249,477,6482,ATL,DFW,2025-04-01 11:20:00,2025-04-01 12:49:00,1,Westjet,Delta Air Lines,True,0.544887,2.48
2,cc1,economy,"18390-2504010700--31954,-31825-2-10968-2504011735",253,2205,YTZ,YOW,2025-04-01 07:00:00,2025-04-01 07:59:00,2,Porter Airlines,Porter Airlines Inc,True,0.462699,0.98
3,cc1,economy,"18390-2504020700--31954,-31825-2-10968-2504021735",253,2205,YTZ,YOW,2025-04-02 07:00:00,2025-04-02 07:59:00,2,Porter Airlines,Porter Airlines Inc,True,0.606563,0.98
4,cc1,economy,"18390-2504021155--31954,-31825-2-10968-2504022254",263,611,ATL,DFW,2025-04-02 21:15:00,2025-04-02 22:54:00,2,Spirit Airlines,Spirit Airlines,True,0.462181,2.65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11122,cc4,first,18467-2509300820--31722-0-10968-2509301042,846,8169,YYZ,DFW,2025-09-30 08:20:00,2025-09-30 10:42:00,0,United Airlines,Air Canada,True,0.668470,3.37
11123,cc4,first,18467-2509301310--32573-1-10968-2509301744,582,3606,YYZ,ORD,2025-09-30 13:10:00,2025-09-30 14:05:00,1,American Airlines,Envoy Air,True,0.590065,1.92
11124,cc4,first,18467-2509301310--32573-1-10968-2509301744,582,2429,ORD,DFW,2025-09-30 15:15:00,2025-09-30 17:44:00,1,American Airlines,American Airlines,True,0.590065,2.48
11125,cc4,first,18467-2509301130--32573-1-10968-2509301841,582,3604,YYZ,ORD,2025-09-30 11:30:00,2025-09-30 12:25:00,1,American Airlines,Envoy Air,True,0.362377,1.92
11126,cc4,first,18467-2509301130--32573-1-10968-2509301841,582,1193,ORD,DFW,2025-09-30 16:12:00,2025-09-30 18:41:00,1,American Airlines,American Airlines,True,0.362377,2.48

In [151]:
class_flight_price_df= class_flight_price_df.drop(columns='cabin_class', errors="ignore")           
class_flight_price_df

,cabin_class_id,itinerary_id,one_way_price_candollar,flight_number,origin_airport,destination_airport,departure_date_time,arrival_date_time,stop_count,marketing_airline,operating_airline,is_self_transfer,score,duration_in_hours
0,cc1,18467-2504010745--31679-1-10968-2504011249,477,6340,YYZ,ATL,2025-04-01 07:45:00,2025-04-01 10:17:00,1,Westjet,Delta Air Lines,True,0.544887,2.53
1,cc1,18467-2504010745--31679-1-10968-2504011249,477,6482,ATL,DFW,2025-04-01 11:20:00,2025-04-01 12:49:00,1,Westjet,Delta Air Lines,True,0.544887,2.48
2,cc1,"18390-2504010700--31954,-31825-2-10968-2504011735",253,2205,YTZ,YOW,2025-04-01 07:00:00,2025-04-01 07:59:00,2,Porter Airlines,Porter Airlines Inc,True,0.462699,0.98
3,cc1,"18390-2504020700--31954,-31825-2-10968-2504021735",253,2205,YTZ,YOW,2025-04-02 07:00:00,2025-04-02 07:59:00,2,Porter Airlines,Porter Airlines Inc,True,0.606563,0.98
4,cc1,"18390-2504021155--31954,-31825-2-10968-2504022254",263,611,ATL,DFW,2025-04-02 21:15:00,2025-04-02 22:54:00,2,Spirit Airlines,Spirit Airlines,True,0.462181,2.65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11122,cc4,18467-2509300820--31722-0-10968-2509301042,846,8169,YYZ,DFW,2025-09-30 08:20:00,2025-09-30 10:42:00,0,United Airlines,Air Canada,True,0.668470,3.37
11123,cc4,18467-2509301310--32573-1-10968-2509301744,582,3606,YYZ,ORD,2025-09-30 13:10:00,2025-09-30 14:05:00,1,American Airlines,Envoy Air,True,0.590065,1.92
11124,cc4,18467-2509301310--32573-1-10968-2509301744,582,2429,ORD,DFW,2025-09-30 15:15:00,2025-09-30 17:44:00,1,American Airlines,American Airlines,True,0.590065,2.48
11125,cc4,18467-2509301130--32573-1-10968-2509301841,582,3604,YYZ,ORD,2025-09-30 11:30:00,2025-09-30 12:25:00,1,American Airlines,Envoy Air,True,0.362377,1.92
11126,cc4,18467-2509301130--32573-1-10968-2509301841,582,1193,ORD,DFW,2025-09-30 16:12:00,2025-09-30 18:41:00,1,American Airlines,American Airlines,True,0.362377,2.48

# Merging  flight_number with class_flight_price

In [152]:
flight_number_df= pd.merge(class_flight_price_df,unique_flights_df, on='flight_number')
flight_number_df

,cabin_class_id,itinerary_id,one_way_price_candollar,flight_number,origin_airport,destination_airport,departure_date_time,arrival_date_time,stop_count,marketing_airline,operating_airline,is_self_transfer,score,duration_in_hours,flight_id
0,cc1,18467-2504010745--31679-1-10968-2504011249,477,6340,YYZ,ATL,2025-04-01 07:45:00,2025-04-01 10:17:00,1,Westjet,Delta Air Lines,True,0.544887,2.53,1
1,cc1,18467-2504010745--31679-1-10968-2504011249,477,6482,ATL,DFW,2025-04-01 11:20:00,2025-04-01 12:49:00,1,Westjet,Delta Air Lines,True,0.544887,2.48,2
2,cc1,"18390-2504010700--31954,-31825-2-10968-2504011735",253,2205,YTZ,YOW,2025-04-01 07:00:00,2025-04-01 07:59:00,2,Porter Airlines,Porter Airlines Inc,True,0.462699,0.98,3
3,cc1,"18390-2504020700--31954,-31825-2-10968-2504021735",253,2205,YTZ,YOW,2025-04-02 07:00:00,2025-04-02 07:59:00,2,Porter Airlines,Porter Airlines Inc,True,0.606563,0.98,3
4,cc1,"18390-2504021155--31954,-31825-2-10968-2504022254",263,611,ATL,DFW,2025-04-02 21:15:00,2025-04-02 22:54:00,2,Spirit Airlines,Spirit Airlines,True,0.462181,2.65,19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11122,cc4,18467-2509300820--31722-0-10968-2509301042,846,8169,YYZ,DFW,2025-09-30 08:20:00,2025-09-30 10:42:00,0,United Airlines,Air Canada,True,0.668470,3.37,83
11123,cc4,18467-2509301310--32573-1-10968-2509301744,582,3606,YYZ,ORD,2025-09-30 13:10:00,2025-09-30 14:05:00,1,American Airlines,Envoy Air,True,0.590065,1.92,30
11124,cc4,18467-2509301310--32573-1-10968-2509301744,582,2429,ORD,DFW,2025-09-30 15:15:00,2025-09-30 17:44:00,1,American Airlines,American Airlines,True,0.590065,2.48,194
11125,cc4,18467-2509301130--32573-1-10968-2509301841,582,3604,YYZ,ORD,2025-09-30 11:30:00,2025-09-30 12:25:00,1,American Airlines,Envoy Air,True,0.362377,1.92,61
11126,cc4,18467-2509301130--32573-1-10968-2509301841,582,1193,ORD,DFW,2025-09-30 16:12:00,2025-09-30 18:41:00,1,American Airlines,American Airlines,True,0.362377,2.48,148

In [153]:
flight_number_df= flight_number_df.drop(columns='flight_number', errors="ignore")           
flight_number_df

,cabin_class_id,itinerary_id,one_way_price_candollar,origin_airport,destination_airport,departure_date_time,arrival_date_time,stop_count,marketing_airline,operating_airline,is_self_transfer,score,duration_in_hours,flight_id
0,cc1,18467-2504010745--31679-1-10968-2504011249,477,YYZ,ATL,2025-04-01 07:45:00,2025-04-01 10:17:00,1,Westjet,Delta Air Lines,True,0.544887,2.53,1
1,cc1,18467-2504010745--31679-1-10968-2504011249,477,ATL,DFW,2025-04-01 11:20:00,2025-04-01 12:49:00,1,Westjet,Delta Air Lines,True,0.544887,2.48,2
2,cc1,"18390-2504010700--31954,-31825-2-10968-2504011735",253,YTZ,YOW,2025-04-01 07:00:00,2025-04-01 07:59:00,2,Porter Airlines,Porter Airlines Inc,True,0.462699,0.98,3
3,cc1,"18390-2504020700--31954,-31825-2-10968-2504021735",253,YTZ,YOW,2025-04-02 07:00:00,2025-04-02 07:59:00,2,Porter Airlines,Porter Airlines Inc,True,0.606563,0.98,3
4,cc1,"18390-2504021155--31954,-31825-2-10968-2504022254",263,ATL,DFW,2025-04-02 21:15:00,2025-04-02 22:54:00,2,Spirit Airlines,Spirit Airlines,True,0.462181,2.65,19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11122,cc4,18467-2509300820--31722-0-10968-2509301042,846,YYZ,DFW,2025-09-30 08:20:00,2025-09-30 10:42:00,0,United Airlines,Air Canada,True,0.668470,3.37,83
11123,cc4,18467-2509301310--32573-1-10968-2509301744,582,YYZ,ORD,2025-09-30 13:10:00,2025-09-30 14:05:00,1,American Airlines,Envoy Air,True,0.590065,1.92,30
11124,cc4,18467-2509301310--32573-1-10968-2509301744,582,ORD,DFW,2025-09-30 15:15:00,2025-09-30 17:44:00,1,American Airlines,American Airlines,True,0.590065,2.48,194
11125,cc4,18467-2509301130--32573-1-10968-2509301841,582,YYZ,ORD,2025-09-30 11:30:00,2025-09-30 12:25:00,1,American Airlines,Envoy Air,True,0.362377,1.92,61
11126,cc4,18467-2509301130--32573-1-10968-2509301841,582,ORD,DFW,2025-09-30 16:12:00,2025-09-30 18:41:00,1,American Airlines,American Airlines,True,0.362377,2.48,148

In [154]:
itinerary_number_df= pd.merge(flight_number_df,itinerary_df, left_on='itinerary_id', right_on='itineraries').rename(columns={'itinerary_id_y':'itinerary_id'})
itinerary_number_df

,cabin_class_id,itinerary_id_x,one_way_price_candollar,origin_airport,destination_airport,departure_date_time,arrival_date_time,stop_count,marketing_airline,operating_airline,is_self_transfer,score,duration_in_hours,flight_id,itinerary_id,itineraries
0,cc1,18467-2504010745--31679-1-10968-2504011249,477,YYZ,ATL,2025-04-01 07:45:00,2025-04-01 10:17:00,1,Westjet,Delta Air Lines,True,0.544887,2.53,1,it1,18467-2504010745--31679-1-10968-2504011249
1,cc1,18467-2504010745--31679-1-10968-2504011249,477,ATL,DFW,2025-04-01 11:20:00,2025-04-01 12:49:00,1,Westjet,Delta Air Lines,True,0.544887,2.48,2,it1,18467-2504010745--31679-1-10968-2504011249
2,cc1,"18390-2504010700--31954,-31825-2-10968-2504011735",253,YTZ,YOW,2025-04-01 07:00:00,2025-04-01 07:59:00,2,Porter Airlines,Porter Airlines Inc,True,0.462699,0.98,3,it2,"18390-2504010700--31954,-31825-2-10968-2504011735"
3,cc1,"18390-2504020700--31954,-31825-2-10968-2504021735",253,YTZ,YOW,2025-04-02 07:00:00,2025-04-02 07:59:00,2,Porter Airlines,Porter Airlines Inc,True,0.606563,0.98,3,it14,"18390-2504020700--31954,-31825-2-10968-2504021735"
4,cc1,"18390-2504021155--31954,-31825-2-10968-2504022254",263,ATL,DFW,2025-04-02 21:15:00,2025-04-02 22:54:00,2,Spirit Airlines,Spirit Airlines,True,0.462181,2.65,19,it15,"18390-2504021155--31954,-31825-2-10968-2504022254"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11122,cc4,18467-2509300820--31722-0-10968-2509301042,846,YYZ,DFW,2025-09-30 08:20:00,2025-09-30 10:42:00,0,United Airlines,Air Canada,True,0.668470,3.37,83,it6326,18467-2509300820--31722-0-10968-2509301042
11123,cc4,18467-2509301310--32573-1-10968-2509301744,582,YYZ,ORD,2025-09-30 13:10:00,2025-09-30 14:05:00,1,American Airlines,Envoy Air,True,0.590065,1.92,30,it6317,18467-2509301310--32573-1-10968-2509301744
11124,cc4,18467-2509301310--32573-1-10968-2509301744,582,ORD,DFW,2025-09-30 15:15:00,2025-09-30 17:44:00,1,American Airlines,American Airlines,True,0.590065,2.48,194,it6317,18467-2509301310--32573-1-10968-2509301744
11125,cc4,18467-2509301130--32573-1-10968-2509301841,582,YYZ,ORD,2025-09-30 11:30:00,2025-09-30 12:25:00,1,American Airlines,Envoy Air,True,0.362377,1.92,61,it6327,18467-2509301130--32573-1-10968-2509301841
11126,cc4,18467-2509301130--32573-1-10968-2509301841,582,ORD,DFW,2025-09-30 16:12:00,2025-09-30 18:41:00,1,American Airlines,American Airlines,True,0.362377,2.48,148,it6327,18467-2509301130--32573-1-10968-2509301841

In [155]:
itinerary_number_df= itinerary_number_df.drop(columns=['itinerary_id_x','itineraries'], errors="ignore")           
itinerary_number_df

,cabin_class_id,one_way_price_candollar,origin_airport,destination_airport,departure_date_time,arrival_date_time,stop_count,marketing_airline,operating_airline,is_self_transfer,score,duration_in_hours,flight_id,itinerary_id
0,cc1,477,YYZ,ATL,2025-04-01 07:45:00,2025-04-01 10:17:00,1,Westjet,Delta Air Lines,True,0.544887,2.53,1,it1
1,cc1,477,ATL,DFW,2025-04-01 11:20:00,2025-04-01 12:49:00,1,Westjet,Delta Air Lines,True,0.544887,2.48,2,it1
2,cc1,253,YTZ,YOW,2025-04-01 07:00:00,2025-04-01 07:59:00,2,Porter Airlines,Porter Airlines Inc,True,0.462699,0.98,3,it2
3,cc1,253,YTZ,YOW,2025-04-02 07:00:00,2025-04-02 07:59:00,2,Porter Airlines,Porter Airlines Inc,True,0.606563,0.98,3,it14
4,cc1,263,ATL,DFW,2025-04-02 21:15:00,2025-04-02 22:54:00,2,Spirit Airlines,Spirit Airlines,True,0.462181,2.65,19,it15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11122,cc4,846,YYZ,DFW,2025-09-30 08:20:00,2025-09-30 10:42:00,0,United Airlines,Air Canada,True,0.668470,3.37,83,it6326
11123,cc4,582,YYZ,ORD,2025-09-30 13:10:00,2025-09-30 14:05:00,1,American Airlines,Envoy Air,True,0.590065,1.92,30,it6317
11124,cc4,582,ORD,DFW,2025-09-30 15:15:00,2025-09-30 17:44:00,1,American Airlines,American Airlines,True,0.590065,2.48,194,it6317
11125,cc4,582,YYZ,ORD,2025-09-30 11:30:00,2025-09-30 12:25:00,1,American Airlines,Envoy Air,True,0.362377,1.92,61,it6327
11126,cc4,582,ORD,DFW,2025-09-30 16:12:00,2025-09-30 18:41:00,1,American Airlines,American Airlines,True,0.362377,2.48,148,it6327

In [156]:
# Merge for origin_airport_id
airport_merged_df = itinerary_number_df.merge(
    airports_df[['airport_id', 'iata code']], 
    left_on='origin_airport', 
    right_on='iata code', 
    how='left'
).rename(columns={'airport_id': 'origin_airport_id'})

# Drop redundant column
airport_merged_df.drop(columns=['iata code'], inplace=True)
airport_merged_df

,cabin_class_id,one_way_price_candollar,origin_airport,destination_airport,departure_date_time,arrival_date_time,stop_count,marketing_airline,operating_airline,is_self_transfer,score,duration_in_hours,flight_id,itinerary_id,origin_airport_id
0,cc1,477,YYZ,ATL,2025-04-01 07:45:00,2025-04-01 10:17:00,1,Westjet,Delta Air Lines,True,0.544887,2.53,1,it1,ap5
1,cc1,477,ATL,DFW,2025-04-01 11:20:00,2025-04-01 12:49:00,1,Westjet,Delta Air Lines,True,0.544887,2.48,2,it1,ap9
2,cc1,253,YTZ,YOW,2025-04-01 07:00:00,2025-04-01 07:59:00,2,Porter Airlines,Porter Airlines Inc,True,0.462699,0.98,3,it2,ap1
3,cc1,253,YTZ,YOW,2025-04-02 07:00:00,2025-04-02 07:59:00,2,Porter Airlines,Porter Airlines Inc,True,0.606563,0.98,3,it14,ap1
4,cc1,263,ATL,DFW,2025-04-02 21:15:00,2025-04-02 22:54:00,2,Spirit Airlines,Spirit Airlines,True,0.462181,2.65,19,it15,ap9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11122,cc4,846,YYZ,DFW,2025-09-30 08:20:00,2025-09-30 10:42:00,0,United Airlines,Air Canada,True,0.668470,3.37,83,it6326,ap5
11123,cc4,582,YYZ,ORD,2025-09-30 13:10:00,2025-09-30 14:05:00,1,American Airlines,Envoy Air,True,0.590065,1.92,30,it6317,ap5
11124,cc4,582,ORD,DFW,2025-09-30 15:15:00,2025-09-30 17:44:00,1,American Airlines,American Airlines,True,0.590065,2.48,194,it6317,ap6
11125,cc4,582,YYZ,ORD,2025-09-30 11:30:00,2025-09-30 12:25:00,1,American Airlines,Envoy Air,True,0.362377,1.92,61,it6327,ap5
11126,cc4,582,ORD,DFW,2025-09-30 16:12:00,2025-09-30 18:41:00,1,American Airlines,American Airlines,True,0.362377,2.48,148,it6327,ap6

In [157]:
# Merge for destination_airport_id 
airport_merged_df = airport_merged_df.merge(
    airports_df[['airport_id', 'iata code']], 
    left_on='destination_airport', 
    right_on='iata code', 
    how='left'
).rename(columns={'airport_id': 'destination_airport_id'})

# Drop redundant column
airport_merged_df.drop(columns=['iata code'], inplace=True)

# Display final DataFrame
airport_merged_df

,cabin_class_id,one_way_price_candollar,origin_airport,destination_airport,departure_date_time,arrival_date_time,stop_count,marketing_airline,operating_airline,is_self_transfer,score,duration_in_hours,flight_id,itinerary_id,origin_airport_id,destination_airport_id
0,cc1,477,YYZ,ATL,2025-04-01 07:45:00,2025-04-01 10:17:00,1,Westjet,Delta Air Lines,True,0.544887,2.53,1,it1,ap5,ap9
1,cc1,477,ATL,DFW,2025-04-01 11:20:00,2025-04-01 12:49:00,1,Westjet,Delta Air Lines,True,0.544887,2.48,2,it1,ap9,ap7
2,cc1,253,YTZ,YOW,2025-04-01 07:00:00,2025-04-01 07:59:00,2,Porter Airlines,Porter Airlines Inc,True,0.462699,0.98,3,it2,ap1,ap4
3,cc1,253,YTZ,YOW,2025-04-02 07:00:00,2025-04-02 07:59:00,2,Porter Airlines,Porter Airlines Inc,True,0.606563,0.98,3,it14,ap1,ap4
4,cc1,263,ATL,DFW,2025-04-02 21:15:00,2025-04-02 22:54:00,2,Spirit Airlines,Spirit Airlines,True,0.462181,2.65,19,it15,ap9,ap7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11122,cc4,846,YYZ,DFW,2025-09-30 08:20:00,2025-09-30 10:42:00,0,United Airlines,Air Canada,True,0.668470,3.37,83,it6326,ap5,ap7
11123,cc4,582,YYZ,ORD,2025-09-30 13:10:00,2025-09-30 14:05:00,1,American Airlines,Envoy Air,True,0.590065,1.92,30,it6317,ap5,ap6
11124,cc4,582,ORD,DFW,2025-09-30 15:15:00,2025-09-30 17:44:00,1,American Airlines,American Airlines,True,0.590065,2.48,194,it6317,ap6,ap7
11125,cc4,582,YYZ,ORD,2025-09-30 11:30:00,2025-09-30 12:25:00,1,American Airlines,Envoy Air,True,0.362377,1.92,61,it6327,ap5,ap6
11126,cc4,582,ORD,DFW,2025-09-30 16:12:00,2025-09-30 18:41:00,1,American Airlines,American Airlines,True,0.362377,2.48,148,it6327,ap6,ap7

In [158]:
# Merge for operating_airline_id
airline_merged_df = airport_merged_df.merge(
    airlines_df[['airline_id', 'airline_name']], 
    left_on='operating_airline', 
    right_on='airline_name',
    how='left'
).rename(columns={'airline_id': 'operating_airline_id'})

# Drop redundant column
airline_merged_df.drop(columns=['airline_name'], inplace=True)

# Merge for marketing_airline_id **without overwriting airline_merged_df**
airline_merged_df = airline_merged_df.merge(
    airlines_df[['airline_id', 'airline_name']], 
    left_on='marketing_airline', 
    right_on='airline_name',
    how='left',
    suffixes=('', '_marketing')  # Prevent overwriting columns
).rename(columns={'airline_id': 'marketing_airline_id'})

# Drop redundant column
airline_merged_df.drop(columns=['airline_name','origin_airport','destination_airport','marketing_airline','operating_airline'], inplace=True)

# Display final DataFrame
airline_merged_df

,cabin_class_id,one_way_price_candollar,departure_date_time,arrival_date_time,stop_count,is_self_transfer,score,duration_in_hours,flight_id,itinerary_id,origin_airport_id,destination_airport_id,operating_airline_id,marketing_airline_id
0,cc1,477,2025-04-01 07:45:00,2025-04-01 10:17:00,1,True,0.544887,2.53,1,it1,ap5,ap9,al4,al16
1,cc1,477,2025-04-01 11:20:00,2025-04-01 12:49:00,1,True,0.544887,2.48,2,it1,ap9,ap7,al4,al16
2,cc1,253,2025-04-01 07:00:00,2025-04-01 07:59:00,2,True,0.462699,0.98,3,it2,ap1,ap4,al10,al11
3,cc1,253,2025-04-02 07:00:00,2025-04-02 07:59:00,2,True,0.606563,0.98,3,it14,ap1,ap4,al10,al11
4,cc1,263,2025-04-02 21:15:00,2025-04-02 22:54:00,2,True,0.462181,2.65,19,it15,ap9,ap7,al14,al14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11122,cc4,846,2025-09-30 08:20:00,2025-09-30 10:42:00,0,True,0.668470,3.37,83,it6326,ap5,ap7,al3,al15
11123,cc4,582,2025-09-30 13:10:00,2025-09-30 14:05:00,1,True,0.590065,1.92,30,it6317,ap5,ap6,al5,al2
11124,cc4,582,2025-09-30 15:15:00,2025-09-30 17:44:00,1,True,0.590065,2.48,194,it6317,ap6,ap7,al2,al2
11125,cc4,582,2025-09-30 11:30:00,2025-09-30 12:25:00,1,True,0.362377,1.92,61,it6327,ap5,ap6,al5,al2
11126,cc4,582,2025-09-30 16:12:00,2025-09-30 18:41:00,1,True,0.362377,2.48,148,it6327,ap6,ap7,al2,al2

In [159]:
airline_merged_df.columns

Index(['cabin_class_id', 'one_way_price_candollar', 'departure_date_time',
       'arrival_date_time', 'stop_count', 'is_self_transfer', 'score',
       'duration_in_hours', 'flight_id', 'itinerary_id', 'origin_airport_id',
       'destination_airport_id', 'operating_airline_id',
       'marketing_airline_id'],
      dtype='object')

In [160]:
mapped_flight_data = airline_merged_df[['itinerary_id','flight_id','origin_airport_id','destination_airport_id','departure_date_time','arrival_date_time','one_way_price_candollar','cabin_class_id',
                                        'stop_count','duration_in_hours','is_self_transfer','operating_airline_id','marketing_airline_id','score']]

In [161]:
airline_merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11127 entries, 0 to 11126
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   cabin_class_id           11127 non-null  object
 1   one_way_price_candollar  11127 non-null  int64
 2   departure_date_time      11127 non-null  object
 3   arrival_date_time        11127 non-null  object
 4   stop_count               11127 non-null  int64
 5   is_self_transfer         11127 non-null  bool
 6   score                    11127 non-null  float64
 7   duration_in_hours        11127 non-null  float64
 8   flight_id                11127 non-null  int64
 9   itinerary_id             11127 non-null  object
 10  origin_airport_id        11127 non-null  object
 11  destination_airport_id   11127 non-null  object
 12  operating_airline_id     11127 non-null  object
 13  marketing_airline_id     11127 non-null  object
dtypes: bool(1), float64(2), int64(3), object(8)
memory usage: 1.1+ MB

In [163]:
airline_merged_df.to_csv('complete_data.csv',index=False)

# Merge itinerary_details with flight_number, itinerary_id, origin_airport, destination_airport

In [164]:
itinerary_details = pd.merge(itinerary_details_df,unique_flights_df, how='left', on='flight_number')
itinerary_details

,itinerary_id,flight_number,origin_airport,destination_airport,departure_date_time,arrival_date_time,is_self_transfer,flight_id
0,18467-2504010745--31679-1-10968-2504011249,6340,YYZ,ATL,2025-04-01 07:45:00,2025-04-01 10:17:00,True,1
1,18467-2504010745--31679-1-10968-2504011249,6482,ATL,DFW,2025-04-01 11:20:00,2025-04-01 12:49:00,True,2
2,"18390-2504010700--31954,-31825-2-10968-2504011735",2205,YTZ,YOW,2025-04-01 07:00:00,2025-04-01 07:59:00,True,3
3,18467-2504010615--32385-1-10910-2504011111,2662,YYZ,ATL,2025-04-01 06:15:00,2025-04-01 08:49:00,True,4
4,18467-2504010745--32385-1-10968-2504011249,2988,YYZ,ATL,2025-04-01 07:45:00,2025-04-01 10:17:00,True,5
...,...,...,...,...,...,...,...,...
11122,18467-2509300820--31722-0-10968-2509301042,8169,YYZ,DFW,2025-09-30 08:20:00,2025-09-30 10:42:00,True,83
11123,18467-2509301310--32573-1-10968-2509301744,3606,YYZ,ORD,2025-09-30 13:10:00,2025-09-30 14:05:00,True,30
11124,18467-2509301310--32573-1-10968-2509301744,2429,ORD,DFW,2025-09-30 15:15:00,2025-09-30 17:44:00,True,194
11125,18467-2509301130--32573-1-10968-2509301841,3604,YYZ,ORD,2025-09-30 11:30:00,2025-09-30 12:25:00,True,61
11126,18467-2509301130--32573-1-10968-2509301841,1193,ORD,DFW,2025-09-30 16:12:00,2025-09-30 18:41:00,True,148

In [165]:
itineraries_df = pd.merge(itinerary_details,itinerary_df, how='left', left_on='itinerary_id', right_on='itineraries').rename(columns={'itinerary_id_y':'itinerary_id'})
itineraries_df

,itinerary_id_x,flight_number,origin_airport,destination_airport,departure_date_time,arrival_date_time,is_self_transfer,flight_id,itinerary_id,itineraries
0,18467-2504010745--31679-1-10968-2504011249,6340,YYZ,ATL,2025-04-01 07:45:00,2025-04-01 10:17:00,True,1,it1,18467-2504010745--31679-1-10968-2504011249
1,18467-2504010745--31679-1-10968-2504011249,6482,ATL,DFW,2025-04-01 11:20:00,2025-04-01 12:49:00,True,2,it1,18467-2504010745--31679-1-10968-2504011249
2,"18390-2504010700--31954,-31825-2-10968-2504011735",2205,YTZ,YOW,2025-04-01 07:00:00,2025-04-01 07:59:00,True,3,it2,"18390-2504010700--31954,-31825-2-10968-2504011735"
3,18467-2504010615--32385-1-10910-2504011111,2662,YYZ,ATL,2025-04-01 06:15:00,2025-04-01 08:49:00,True,4,it3,18467-2504010615--32385-1-10910-2504011111
4,18467-2504010745--32385-1-10968-2504011249,2988,YYZ,ATL,2025-04-01 07:45:00,2025-04-01 10:17:00,True,5,it4,18467-2504010745--32385-1-10968-2504011249
...,...,...,...,...,...,...,...,...,...,...
11122,18467-2509300820--31722-0-10968-2509301042,8169,YYZ,DFW,2025-09-30 08:20:00,2025-09-30 10:42:00,True,83,it6326,18467-2509300820--31722-0-10968-2509301042
11123,18467-2509301310--32573-1-10968-2509301744,3606,YYZ,ORD,2025-09-30 13:10:00,2025-09-30 14:05:00,True,30,it6317,18467-2509301310--32573-1-10968-2509301744
11124,18467-2509301310--32573-1-10968-2509301744,2429,ORD,DFW,2025-09-30 15:15:00,2025-09-30 17:44:00,True,194,it6317,18467-2509301310--32573-1-10968-2509301744
11125,18467-2509301130--32573-1-10968-2509301841,3604,YYZ,ORD,2025-09-30 11:30:00,2025-09-30 12:25:00,True,61,it6327,18467-2509301130--32573-1-10968-2509301841
11126,18467-2509301130--32573-1-10968-2509301841,1193,ORD,DFW,2025-09-30 16:12:00,2025-09-30 18:41:00,True,148,it6327,18467-2509301130--32573-1-10968-2509301841

In [166]:
# Merge for origin_airport_id
itinerary_details_merged_df = itineraries_df.merge(
    airports_df[['airport_id', 'iata code']], 
    left_on='origin_airport', 
    right_on='iata code', 
    how='left'
).rename(columns={'airport_id': 'origin_airport_id'})

# Drop redundant column
itinerary_details_merged_df.drop(columns=['iata code'], inplace=True)

itinerary_details_merged_df = itinerary_details_merged_df.merge(
    airports_df[['airport_id', 'iata code']], 
    left_on='destination_airport', 
    right_on='iata code', 
    how='left'
).rename(columns={'airport_id': 'destination_airport_id'})

# Drop redundant column
itinerary_details_merged_df.drop(columns=['iata code'], inplace=True)

# Display final DataFrame
itinerary_details_merged_df

,itinerary_id_x,flight_number,origin_airport,destination_airport,departure_date_time,arrival_date_time,is_self_transfer,flight_id,itinerary_id,itineraries,origin_airport_id,destination_airport_id
0,18467-2504010745--31679-1-10968-2504011249,6340,YYZ,ATL,2025-04-01 07:45:00,2025-04-01 10:17:00,True,1,it1,18467-2504010745--31679-1-10968-2504011249,ap5,ap9
1,18467-2504010745--31679-1-10968-2504011249,6482,ATL,DFW,2025-04-01 11:20:00,2025-04-01 12:49:00,True,2,it1,18467-2504010745--31679-1-10968-2504011249,ap9,ap7
2,"18390-2504010700--31954,-31825-2-10968-2504011735",2205,YTZ,YOW,2025-04-01 07:00:00,2025-04-01 07:59:00,True,3,it2,"18390-2504010700--31954,-31825-2-10968-2504011735",ap1,ap4
3,18467-2504010615--32385-1-10910-2504011111,2662,YYZ,ATL,2025-04-01 06:15:00,2025-04-01 08:49:00,True,4,it3,18467-2504010615--32385-1-10910-2504011111,ap5,ap9
4,18467-2504010745--32385-1-10968-2504011249,2988,YYZ,ATL,2025-04-01 07:45:00,2025-04-01 10:17:00,True,5,it4,18467-2504010745--32385-1-10968-2504011249,ap5,ap9
...,...,...,...,...,...,...,...,...,...,...,...,...
11122,18467-2509300820--31722-0-10968-2509301042,8169,YYZ,DFW,2025-09-30 08:20:00,2025-09-30 10:42:00,True,83,it6326,18467-2509300820--31722-0-10968-2509301042,ap5,ap7
11123,18467-2509301310--32573-1-10968-2509301744,3606,YYZ,ORD,2025-09-30 13:10:00,2025-09-30 14:05:00,True,30,it6317,18467-2509301310--32573-1-10968-2509301744,ap5,ap6
11124,18467-2509301310--32573-1-10968-2509301744,2429,ORD,DFW,2025-09-30 15:15:00,2025-09-30 17:44:00,True,194,it6317,18467-2509301310--32573-1-10968-2509301744,ap6,ap7
11125,18467-2509301130--32573-1-10968-2509301841,3604,YYZ,ORD,2025-09-30 11:30:00,2025-09-30 12:25:00,True,61,it6327,18467-2509301130--32573-1-10968-2509301841,ap5,ap6
11126,18467-2509301130--32573-1-10968-2509301841,1193,ORD,DFW,2025-09-30 16:12:00,2025-09-30 18:41:00,True,148,it6327,18467-2509301130--32573-1-10968-2509301841,ap6,ap7

In [167]:
itinerary_details_merged_df.drop(columns=['itinerary_id_x','flight_number','itineraries','origin_airport','destination_airport'],errors='ignore')

,departure_date_time,arrival_date_time,is_self_transfer,flight_id,itinerary_id,origin_airport_id,destination_airport_id
0,2025-04-01 07:45:00,2025-04-01 10:17:00,True,1,it1,ap5,ap9
1,2025-04-01 11:20:00,2025-04-01 12:49:00,True,2,it1,ap9,ap7
2,2025-04-01 07:00:00,2025-04-01 07:59:00,True,3,it2,ap1,ap4
3,2025-04-01 06:15:00,2025-04-01 08:49:00,True,4,it3,ap5,ap9
4,2025-04-01 07:45:00,2025-04-01 10:17:00,True,5,it4,ap5,ap9
...,...,...,...,...,...,...,...
11122,2025-09-30 08:20:00,2025-09-30 10:42:00,True,83,it6326,ap5,ap7
11123,2025-09-30 13:10:00,2025-09-30 14:05:00,True,30,it6317,ap5,ap6
11124,2025-09-30 15:15:00,2025-09-30 17:44:00,True,194,it6317,ap6,ap7
11125,2025-09-30 11:30:00,2025-09-30 12:25:00,True,61,it6327,ap5,ap6
11126,2025-09-30 16:12:00,2025-09-30 18:41:00,True,148,it6327,ap6,ap7

# Merge airport with country_code

In [173]:
airport_data = pd.merge(airports_df,unique_country_code,left_on='country', right_on='country_code', how='left')
airport_data

,name,iata code,country,city,latitude,longitude,timezone,departures,airport_id,country_code_id,country_code
0,Billy Bishop Toronto City Airport,YTZ,CA,Toronto,752.0,-79.39828,EST,752,ap1,coc2,CA
1,Kitchener/Waterloo Airport,YKF,CA,Breslau,454.0,-80.38593,EST,454,ap2,coc2,CA
2,Montreal-Pierre Elliott Trudeau International ...,YUL,CA,Montreal,35190.0,-73.75019,EST,35190,ap3,coc2,CA
3,Ottawa Macdonald-Cartier International Airport,YOW,CA,Ottawa,10293.0,-75.66917,EST,10293,ap4,coc2,CA
4,Toronto Pearson International Airport,YYZ,CA,Toronto,72355.0,-79.61286,EST,72355,ap5,coc2,CA
5,Chicago O'Hare International Airport,ORD,US,Chicago,177167.0,-87.90446,CST,177167,ap6,coc1,US
6,Dallas/Fort Worth International Airport,DFW,US,Dallas-Ft Worth,172447.0,-97.03720,CST,172447,ap7,coc1,US
7,Denver International Airport,DEN,US,Denver,100565.0,-104.67326,MST,100565,ap8,coc1,US
8,Hartsfield-Jackson Atlanta International Airport,ATL,US,Atlanta,168164.0,-84.42265,EST,168164,ap9,coc1,US
9,Los Angeles International Airport,LAX,US,Los Angeles,112571.0,-118.40897,PST,112571,ap10,coc1,US

In [174]:
airport_data.drop(columns=['country','country_code'], errors='ignore')

,name,iata code,city,latitude,longitude,timezone,departures,airport_id,country_code_id
0,Billy Bishop Toronto City Airport,YTZ,Toronto,752.0,-79.39828,EST,752,ap1,coc2
1,Kitchener/Waterloo Airport,YKF,Breslau,454.0,-80.38593,EST,454,ap2,coc2
2,Montreal-Pierre Elliott Trudeau International ...,YUL,Montreal,35190.0,-73.75019,EST,35190,ap3,coc2
3,Ottawa Macdonald-Cartier International Airport,YOW,Ottawa,10293.0,-75.66917,EST,10293,ap4,coc2
4,Toronto Pearson International Airport,YYZ,Toronto,72355.0,-79.61286,EST,72355,ap5,coc2
5,Chicago O'Hare International Airport,ORD,Chicago,177167.0,-87.90446,CST,177167,ap6,coc1
6,Dallas/Fort Worth International Airport,DFW,Dallas-Ft Worth,172447.0,-97.03720,CST,172447,ap7,coc1
7,Denver International Airport,DEN,Denver,100565.0,-104.67326,MST,100565,ap8,coc1
8,Hartsfield-Jackson Atlanta International Airport,ATL,Atlanta,168164.0,-84.42265,EST,168164,ap9,coc1
9,Los Angeles International Airport,LAX,Los Angeles,112571.0,-118.40897,PST,112571,ap10,coc1

# Merge airline  dataframe with country_code

In [175]:
airline_data = pd.merge(airlines_df,unique_country_code,left_on='country_code', right_on='country_code', how='left')
airline_data

,airline_id,airline_name,iata,country_code,is_airline_passenger,total_aircrafts,average_fleet_age,accidents_last_5y,iosa_registered,iosa_expiry,country_code_id
0,al1,Alaska Airlines,AS,US,True,158,8.1,1,True,2025-01-16 00:00:00+00:00,coc1
1,al2,American Airlines,AA,US,True,684,10.2,26,True,2025-07-29 00:00:00+00:00,coc1
2,al3,Air Canada,AC,CA,True,98,11.7,0,True,2024-04-18 00:00:00+00:00,coc2
3,al4,Delta Air Lines,DL,US,True,591,12.5,22,True,2024-10-17 00:00:00+00:00,coc1
4,al5,Envoy Air,MQ,US,True,161,9.6,0,True,2025-11-18 00:00:00+00:00,coc1
5,al6,Frontier Airlines,F9,US,True,83,3.0,4,True,2024-01-03 00:00:00+00:00,coc1
6,al7,GOL Linhas Aereas Inteligentes,G3,BR,True,103,10.7,0,True,2025-11-23 00:00:00+00:00,coc3
7,al8,Jazz Aviation,QK,CA,True,85,13.8,3,True,2024-10-21 00:00:00+00:00,coc2
8,al9,Lufthansa,LH,DE,True,131,8.9,1,True,2026-05-12 00:00:00+00:00,coc4
9,al10,Porter Airlines Inc,P3,CA,True,1,8.0,0,True,NaT,coc2
10,al11,Porter Airlines,PD,CA,True,1,9.0,0,True,NaT,coc2
11,al12,Republic Airline United Express,YX,US,True,182,10.1,1,True,2024-12-12 00:00:00+00:00,coc1
12,al13,SkyWest Airlines,OO,US,True,462,10.7,3,True,2024-09-25 00:00:00+00:00,coc1
13,al14,Spirit Airlines,NK,US,True,125,4.1,4,True,2025-07-30 00:00:00+00:00,coc1
14,al15,United Airlines,UA,US,True,502,14.1,12,True,2025-02-26 00:00:00+00:00,coc1
15,al16,Westjet,WS,CA,True,70,9.8,5,True,2024-11-27 00:00:00+00:00,coc2
16,al17,American Eagle,AA,US,True,567,10.0,1,True,2024-08-02 00:00:00+00:00,coc1

In [176]:
airline_data.drop(columns=['country_code'])

,airline_id,airline_name,iata,is_airline_passenger,total_aircrafts,average_fleet_age,accidents_last_5y,iosa_registered,iosa_expiry,country_code_id
0,al1,Alaska Airlines,AS,True,158,8.1,1,True,2025-01-16 00:00:00+00:00,coc1
1,al2,American Airlines,AA,True,684,10.2,26,True,2025-07-29 00:00:00+00:00,coc1
2,al3,Air Canada,AC,True,98,11.7,0,True,2024-04-18 00:00:00+00:00,coc2
3,al4,Delta Air Lines,DL,True,591,12.5,22,True,2024-10-17 00:00:00+00:00,coc1
4,al5,Envoy Air,MQ,True,161,9.6,0,True,2025-11-18 00:00:00+00:00,coc1
5,al6,Frontier Airlines,F9,True,83,3.0,4,True,2024-01-03 00:00:00+00:00,coc1
6,al7,GOL Linhas Aereas Inteligentes,G3,True,103,10.7,0,True,2025-11-23 00:00:00+00:00,coc3
7,al8,Jazz Aviation,QK,True,85,13.8,3,True,2024-10-21 00:00:00+00:00,coc2
8,al9,Lufthansa,LH,True,131,8.9,1,True,2026-05-12 00:00:00+00:00,coc4
9,al10,Porter Airlines Inc,P3,True,1,8.0,0,True,NaT,coc2
10,al11,Porter Airlines,PD,True,1,9.0,0,True,NaT,coc2
11,al12,Republic Airline United Express,YX,True,182,10.1,1,True,2024-12-12 00:00:00+00:00,coc1
12,al13,SkyWest Airlines,OO,True,462,10.7,3,True,2024-09-25 00:00:00+00:00,coc1
13,al14,Spirit Airlines,NK,True,125,4.1,4,True,2025-07-30 00:00:00+00:00,coc1
14,al15,United Airlines,UA,True,502,14.1,12,True,2025-02-26 00:00:00+00:00,coc1
15,al16,Westjet,WS,True,70,9.8,5,True,2024-11-27 00:00:00+00:00,coc2
16,al17,American Eagle,AA,True,567,10.0,1,True,2024-08-02 00:00:00+00:00,coc1

# Merge flight_price with itinerary_df, airline_df and unique_cabin_class_df

In [179]:
flight_price_data =pd.merge(flight_price_df,unique_cabin_classes_df, how='left', on='cabin_class' )
flight_price_data

,itinerary_id,cabin_class,stop_count,duration_in_hours,one_way_price_candollar,marketing_airline,operating_airline,cabin_class_id
0,18467-2504010745--31679-1-10968-2504011249,economy,1,2.53,477,Westjet,Delta Air Lines,cc1
1,18467-2504010745--31679-1-10968-2504011249,economy,1,2.48,477,Westjet,Delta Air Lines,cc1
2,"18390-2504010700--31954,-31825-2-10968-2504011735",economy,2,0.98,253,Porter Airlines,Porter Airlines Inc,cc1
3,18467-2504010615--32385-1-10910-2504011111,premium_economy,1,2.57,581,Delta Air Lines,Delta Air Lines,cc2
4,18467-2504010745--32385-1-10968-2504011249,premium_economy,1,2.53,581,Delta Air Lines,Delta Air Lines,cc2
...,...,...,...,...,...,...,...,...
11122,18467-2509300820--31722-0-10968-2509301042,first,0,3.37,846,United Airlines,Air Canada,cc4
11123,18467-2509301310--32573-1-10968-2509301744,first,1,1.92,582,American Airlines,Envoy Air,cc4
11124,18467-2509301310--32573-1-10968-2509301744,first,1,2.48,582,American Airlines,American Airlines,cc4
11125,18467-2509301130--32573-1-10968-2509301841,first,1,1.92,582,American Airlines,Envoy Air,cc4
11126,18467-2509301130--32573-1-10968-2509301841,first,1,2.48,582,American Airlines,American Airlines,cc4

In [182]:
flight_price_data.drop(columns='cabin_class', errors='ignore', inplace=True)
flight_price_data

,itinerary_id,stop_count,duration_in_hours,one_way_price_candollar,marketing_airline,operating_airline,cabin_class_id
0,18467-2504010745--31679-1-10968-2504011249,1,2.53,477,Westjet,Delta Air Lines,cc1
1,18467-2504010745--31679-1-10968-2504011249,1,2.48,477,Westjet,Delta Air Lines,cc1
2,"18390-2504010700--31954,-31825-2-10968-2504011735",2,0.98,253,Porter Airlines,Porter Airlines Inc,cc1
3,18467-2504010615--32385-1-10910-2504011111,1,2.57,581,Delta Air Lines,Delta Air Lines,cc2
4,18467-2504010745--32385-1-10968-2504011249,1,2.53,581,Delta Air Lines,Delta Air Lines,cc2
...,...,...,...,...,...,...,...
11122,18467-2509300820--31722-0-10968-2509301042,0,3.37,846,United Airlines,Air Canada,cc4
11123,18467-2509301310--32573-1-10968-2509301744,1,1.92,582,American Airlines,Envoy Air,cc4
11124,18467-2509301310--32573-1-10968-2509301744,1,2.48,582,American Airlines,American Airlines,cc4
11125,18467-2509301130--32573-1-10968-2509301841,1,1.92,582,American Airlines,Envoy Air,cc4
11126,18467-2509301130--32573-1-10968-2509301841,1,2.48,582,American Airlines,American Airlines,cc4

In [184]:
# Merge for operating_airline_id
price_merged_df = flight_price_data.merge(
    airlines_df[['airline_id', 'airline_name']], 
    left_on='operating_airline', 
    right_on='airline_name',
    how='left'
).rename(columns={'airline_id': 'operating_airline_id'})

# Drop redundant column
price_merged_df.drop(columns=['airline_name'], inplace=True)

# Merge for marketing_airline_id **without overwriting airline_merged_df**
price_merged_df = price_merged_df.merge(
    airlines_df[['airline_id', 'airline_name']], 
    left_on='marketing_airline', 
    right_on='airline_name',
    how='left',
    suffixes=('', '_marketing')  # Prevent overwriting columns
).rename(columns={'airline_id': 'marketing_airline_id'})

# Drop redundant column
price_merged_df.drop(columns=['airline_name','marketing_airline','operating_airline'], inplace=True)

# Display final DataFrame
price_merged_df

,itinerary_id,stop_count,duration_in_hours,one_way_price_candollar,cabin_class_id,operating_airline_id,marketing_airline_id
0,18467-2504010745--31679-1-10968-2504011249,1,2.53,477,cc1,al4,al16
1,18467-2504010745--31679-1-10968-2504011249,1,2.48,477,cc1,al4,al16
2,"18390-2504010700--31954,-31825-2-10968-2504011735",2,0.98,253,cc1,al10,al11
3,18467-2504010615--32385-1-10910-2504011111,1,2.57,581,cc2,al4,al4
4,18467-2504010745--32385-1-10968-2504011249,1,2.53,581,cc2,al4,al4
...,...,...,...,...,...,...,...
11122,18467-2509300820--31722-0-10968-2509301042,0,3.37,846,cc4,al3,al15
11123,18467-2509301310--32573-1-10968-2509301744,1,1.92,582,cc4,al5,al2
11124,18467-2509301310--32573-1-10968-2509301744,1,2.48,582,cc4,al2,al2
11125,18467-2509301130--32573-1-10968-2509301841,1,1.92,582,cc4,al5,al2
11126,18467-2509301130--32573-1-10968-2509301841,1,2.48,582,cc4,al2,al2

In [187]:
itinerary_price_merged_df = pd.merge(price_merged_df, itinerary_df,left_on='itinerary_id', right_on='itineraries', how='left').rename(columns={'itinerary_id_y':'itinerary_id'})
itinerary_price_merged_df

,itinerary_id_x,stop_count,duration_in_hours,one_way_price_candollar,cabin_class_id,operating_airline_id,marketing_airline_id,itinerary_id,itineraries
0,18467-2504010745--31679-1-10968-2504011249,1,2.53,477,cc1,al4,al16,it1,18467-2504010745--31679-1-10968-2504011249
1,18467-2504010745--31679-1-10968-2504011249,1,2.48,477,cc1,al4,al16,it1,18467-2504010745--31679-1-10968-2504011249
2,"18390-2504010700--31954,-31825-2-10968-2504011735",2,0.98,253,cc1,al10,al11,it2,"18390-2504010700--31954,-31825-2-10968-2504011735"
3,18467-2504010615--32385-1-10910-2504011111,1,2.57,581,cc2,al4,al4,it3,18467-2504010615--32385-1-10910-2504011111
4,18467-2504010745--32385-1-10968-2504011249,1,2.53,581,cc2,al4,al4,it4,18467-2504010745--32385-1-10968-2504011249
...,...,...,...,...,...,...,...,...,...
11122,18467-2509300820--31722-0-10968-2509301042,0,3.37,846,cc4,al3,al15,it6326,18467-2509300820--31722-0-10968-2509301042
11123,18467-2509301310--32573-1-10968-2509301744,1,1.92,582,cc4,al5,al2,it6317,18467-2509301310--32573-1-10968-2509301744
11124,18467-2509301310--32573-1-10968-2509301744,1,2.48,582,cc4,al2,al2,it6317,18467-2509301310--32573-1-10968-2509301744
11125,18467-2509301130--32573-1-10968-2509301841,1,1.92,582,cc4,al5,al2,it6327,18467-2509301130--32573-1-10968-2509301841
11126,18467-2509301130--32573-1-10968-2509301841,1,2.48,582,cc4,al2,al2,it6327,18467-2509301130--32573-1-10968-2509301841

In [190]:
itinerary_price_merged_df.drop(columns=['itineraries','itinerary_id_x'], errors='ignore', inplace=True)

In [191]:
itinerary_price_merged_df

,stop_count,duration_in_hours,one_way_price_candollar,cabin_class_id,operating_airline_id,marketing_airline_id,itinerary_id
0,1,2.53,477,cc1,al4,al16,it1
1,1,2.48,477,cc1,al4,al16,it1
2,2,0.98,253,cc1,al10,al11,it2
3,1,2.57,581,cc2,al4,al4,it3
4,1,2.53,581,cc2,al4,al4,it4
...,...,...,...,...,...,...,...
11122,0,3.37,846,cc4,al3,al15,it6326
11123,1,1.92,582,cc4,al5,al2,it6317
11124,1,2.48,582,cc4,al2,al2,it6317
11125,1,1.92,582,cc4,al5,al2,it6327
11126,1,2.48,582,cc4,al2,al2,it6327

In [192]:
itinerary_price_merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11127 entries, 0 to 11126
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   stop_count               11127 non-null  int64
 1   duration_in_hours        11127 non-null  float64
 2   one_way_price_candollar  11127 non-null  int64
 3   cabin_class_id           11127 non-null  object
 4   operating_airline_id     11127 non-null  object
 5   marketing_airline_id     11127 non-null  object
 6   itinerary_id             11127 non-null  object
dtypes: float64(1), int64(2), object(4)
memory usage: 608.6+ KB